import type { CardDefinition, CardType, Mechanic, Rarity } from './types';

type Seed = [string, number, Rarity, CardType, Partial<CardDefinition>?];
const C = '#65d4ff', A = '#dff7ff';

const seeds: Seed[] = [
  ['Knight',3,'Common','troop'],['Archers',3,'Common','troop',{count:2,range:4.8,target:'all'}],['Goblins',2,'Common','troop',{count:4,speed:1.25,mechanics:['swarm']}],['Giant',5,'Rare','troop',{hp:2600,damage:170,speed:.55,target:'buildings',mechanics:['tank','buildingOnly']}],['P.E.K.K.A',7,'Epic','troop',{hp:3300,damage:570,speed:.65}],
  ['Minions',3,'Common','troop',{count:3,speed:1.25,target:'all',mechanics:['flying','swarm']}],['Balloon',5,'Epic','troop',{hp:1700,damage:640,speed:.75,target:'buildings',mechanics:['flying','buildingOnly','deathBomb']}],['Witch',5,'Epic','troop',{range:4.8,target:'all',mechanics:['ranged','splash','spawner']}],['Barbarians',5,'Common','troop',{count:5,mechanics:['swarm']}],['Golem',8,'Epic','troop',{hp:5100,damage:220,speed:.42,target:'buildings',mechanics:['tank','buildingOnly','deathSpawn','deathBomb']}],
  ['Skeletons',1,'Common','troop',{count:3,hp:90,damage:78,speed:1.3,mechanics:['swarm']}],['Valkyrie',4,'Rare','troop',{hp:1900,damage:260,mechanics:['splash']}],['Skeleton Army',3,'Epic','troop',{count:12,hp:74,damage:67,speed:1.3,mechanics:['swarm']}],['Bomber',2,'Common','troop',{range:4.5,mechanics:['ranged','splash']}],['Musketeer',4,'Rare','troop',{range:6,target:'all',mechanics:['ranged']}],
  ['Baby Dragon',4,'Epic','troop',{hp:1500,range:3.5,target:'all',mechanics:['flying','ranged','splash']}],['Prince',5,'Epic','troop',{hp:1900,damage:370,mechanics:['charge']}],['Wizard',5,'Rare','troop',{damage:280,range:5.5,target:'all',mechanics:['ranged','splash']}],['Mini P.E.K.K.A',4,'Rare','troop',{damage:520}],['Spear Goblins',2,'Common','troop',{count:3,hp:135,range:4.7,target:'all',mechanics:['ranged','swarm']}],
  ['Giant Skeleton',6,'Epic','troop',{hp:3000,damage:170,mechanics:['tank','deathBomb']}],['Hog Rider',4,'Rare','troop',{hp:1700,damage:260,speed:1.35,target:'buildings',mechanics:['buildingOnly','jump']}],['Minion Horde',5,'Common','troop',{count:6,hp:220,speed:1.25,target:'all',mechanics:['flying','swarm']}],['Ice Wizard',3,'Legendary','troop',{range:5.5,target:'all',mechanics:['ranged','slow','splash']}],['Royal Giant',6,'Common','troop',{hp:3000,damage:300,range:5,target:'buildings',mechanics:['tank','ranged','buildingOnly']}],
  ['Guards',3,'Epic','troop',{count:3,hp:130,mechanics:['swarm','shield']}],['Princess',3,'Legendary','troop',{hp:300,damage:190,range:8.5,target:'all',mechanics:['ranged','splash']}],['Dark Prince',4,'Epic','troop',{hp:1250,damage:220,mechanics:['charge','shield','splash']}],['Three Musketeers',9,'Rare','troop',{count:3,range:6,target:'all',mechanics:['ranged']}],['Lava Hound',7,'Legendary','troop',{hp:3700,damage:55,speed:.5,target:'buildings',mechanics:['flying','tank','buildingOnly','deathSpawn']}],
  ['Ice Spirit',1,'Common','troop',{hp:200,damage:110,speed:1.5,mechanics:['jump','freeze','splash']}],['Fire Spirit',1,'Common','troop',{hp:220,damage:260,speed:1.5,mechanics:['jump','splash']}],['Miner',3,'Legendary','troop',{hp:1100,mechanics:['burrow']}],['Sparky',6,'Legendary','troop',{hp:1300,damage:1100,range:5,hitSpeed:4,mechanics:['ranged','splash']}],['Bowler',5,'Epic','troop',{hp:2100,damage:290,range:5,mechanics:['ranged','splash','knockback']}],
  ['Lumberjack',4,'Legendary','troop',{damage:240,speed:1.3,hitSpeed:.8,mechanics:['rage']}],['Battle Ram',4,'Rare','troop',{hp:1100,damage:420,speed:1.15,target:'buildings',mechanics:['charge','buildingOnly','deathSpawn']}],['Inferno Dragon',4,'Legendary','troop',{range:4,target:'all',mechanics:['flying','beam']}],['Ice Golem',2,'Rare','troop',{hp:1200,damage:85,speed:.55,target:'buildings',mechanics:['tank','buildingOnly','slow','deathBomb']}],['Mega Minion',3,'Rare','troop',{hp:760,damage:300,target:'all',mechanics:['flying']}],
  ['Dart Goblin',3,'Rare','troop',{hp:280,damage:140,speed:1.25,range:6.5,target:'all',mechanics:['ranged']}],['Goblin Gang',3,'Common','troop',{count:6,hp:130,speed:1.25,mechanics:['swarm']}],['Electro Wizard',4,'Legendary','troop',{range:5,target:'all',mechanics:['ranged','stun','chain']}],['Elite Barbarians',6,'Common','troop',{count:2,hp:1300,damage:330,speed:1.3}],['Hunter',4,'Epic','troop',{hp:850,damage:320,range:4,target:'all',mechanics:['ranged','splash']}],
  ['Executioner',5,'Epic','troop',{hp:1200,damage:260,range:4.5,target:'all',mechanics:['ranged','splash']}],['Bandit',3,'Legendary','troop',{hp:850,damage:200,speed:1.2,mechanics:['dash']}],['Royal Recruits',7,'Common','troop',{count:6,hp:900,mechanics:['swarm','shield']}],['Night Witch',4,'Legendary','troop',{mechanics:['spawner','deathSpawn']}],['Bats',2,'Common','troop',{count:5,hp:90,damage:95,speed:1.35,target:'all',mechanics:['flying','swarm']}],
  ['Royal Ghost',3,'Legendary','troop',{damage:220,mechanics:['invisible','splash']}],['Ram Rider',5,'Legendary','troop',{hp:1800,damage:290,target:'buildings',mechanics:['charge','buildingOnly','slow']}],['Zappies',4,'Rare','troop',{count:3,range:5,target:'all',mechanics:['ranged','stun']}],['Rascals',5,'Common','troop',{count:3,hp:900,mechanics:['ranged','swarm']}],['Cannon Cart',5,'Epic','troop',{hp:1300,range:5.5,mechanics:['ranged','shield','transform']}],
  ['Mega Knight',7,'Legendary','troop',{hp:3900,damage:330,mechanics:['tank','jump','splash']}],['Skeleton Barrel',3,'Common','troop',{hp:650,target:'buildings',mechanics:['flying','buildingOnly','deathSpawn','deathBomb']}],['Flying Machine',4,'Rare','troop',{range:6,target:'all',mechanics:['flying','ranged']}],['Wall Breakers',2,'Epic','troop',{count:2,hp:280,damage:520,speed:1.45,target:'buildings',mechanics:['swarm','buildingOnly','deathBomb']}],['Royal Hogs',5,'Rare','troop',{count:4,hp:700,speed:1.25,target:'buildings',mechanics:['swarm','buildingOnly','jump']}],
  ['Goblin Giant',6,'Epic','troop',{hp:3000,target:'buildings',mechanics:['tank','buildingOnly','deathSpawn']}],['Fisherman',3,'Legendary','troop',{hp:900,range:4,mechanics:['pull']}],['Magic Archer',4,'Legendary','troop',{range:7,target:'all',mechanics:['ranged','splash']}],['Electro Dragon',5,'Epic','troop',{target:'all',mechanics:['flying','ranged','chain','stun']}],['Firecracker',3,'Common','troop',{hp:320,range:6,target:'all',mechanics:['ranged','splash','knockback']}],
  ['Mighty Miner',4,'Champion','troop',{hp:2400,mechanics:['beam','ability']}],['Elixir Golem',3,'Rare','troop',{hp:1800,target:'buildings',mechanics:['tank','buildingOnly','deathSpawn']}],['Battle Healer',4,'Rare','troop',{hp:1600,target:'ground',mechanics:['heal']}],['Skeleton King',4,'Champion','troop',{hp:2400,mechanics:['splash','spawn','ability']}],['Archer Queen',5,'Champion','troop',{range:5.5,target:'all',mechanics:['ranged','invisible','ability']}],
  ['Golden Knight',4,'Champion','troop',{hp:1700,mechanics:['dash','ability']}],['Monk',5,'Champion','troop',{hp:2100,mechanics:['knockback','reflect','ability']}],['Skeleton Dragons',4,'Common','troop',{count:2,range:3.5,target:'all',mechanics:['flying','ranged','splash']}],['Mother Witch',4,'Legendary','troop',{range:5.5,target:'all',mechanics:['ranged','transform']}],['Electro Spirit',1,'Common','troop',{hp:190,speed:1.5,target:'all',mechanics:['jump','chain','stun']}],
  ['Electro Giant',7,'Epic','troop',{hp:3800,target:'buildings',mechanics:['tank','buildingOnly','stun','reflect']}],['Phoenix',4,'Legendary','troop',{hp:1000,target:'all',mechanics:['flying','deathSpawn']}],['Heal Spirit',1,'Rare','troop',{hp:190,speed:1.5,mechanics:['jump','heal','splash']}],
  ['Little Prince',3,'Champion','troop',{range:6,target:'all',mechanics:['ranged','ability','spawn']}],['Goblinstein',5,'Champion','troop',{count:2,hp:1500,mechanics:['chain','ability']}],['Goblin Machine',5,'Legendary','troop',{hp:2200,range:5,target:'all',mechanics:['ranged','splash']}],['Goblin Demolisher',4,'Rare','troop',{hp:1200,damage:240,mechanics:['deathBomb']}],['Suspicious Bush',2,'Rare','troop',{count:2,hp:900,speed:.8,target:'buildings',mechanics:['invisible','buildingOnly','deathSpawn']}],
  ['Rune Giant',4,'Epic','troop',{hp:2200,target:'buildings',mechanics:['tank','buildingOnly','rage']}],['Spirit Empress',6,'Legendary','troop',{hp:1500,target:'all',mechanics:['flying','transform','splash']}],['Berserker',2,'Common','troop',{hp:650,hitSpeed:.65,speed:1.25,mechanics:['rage']}],['Boss Bandit',6,'Champion','troop',{hp:2400,damage:280,mechanics:['dash','ability']}],['Ronin',5,'Legendary','troop',{hp:1700,damage:320,mechanics:['dash','shield','splash']}],['Minion Giant',5,'Rare','troop',{hp:2500,speed:.65,target:'buildings',mechanics:['flying','tank','buildingOnly','deathSpawn']}],
  ['Cannon',3,'Common','building',{range:5.5}],['Goblin Hut',5,'Rare','building',{mechanics:['spawner','deathSpawn']}],['Mortar',4,'Common','building',{range:9,mechanics:['siege','splash']}],['Inferno Tower',5,'Rare','building',{range:6,mechanics:['beam']}],['Bomb Tower',4,'Rare','building',{range:5,mechanics:['splash','deathBomb']}],['Barbarian Hut',6,'Rare','building',{mechanics:['spawner','deathSpawn']}],['Tesla',4,'Common','building',{range:5.5,target:'all',mechanics:['invisible']}],['Elixir Collector',6,'Rare','building',{damage:0,mechanics:['spawn']}],['X-Bow',6,'Epic','building',{range:10,hitSpeed:.35,mechanics:['siege']}],['Tombstone',3,'Rare','building',{damage:0,mechanics:['spawner','deathSpawn']}],['Furnace',4,'Rare','building',{mechanics:['spawner']}],['Goblin Cage',4,'Rare','building',{damage:0,mechanics:['deathSpawn']}],['Goblin Drill',4,'Epic','building',{mechanics:['burrow','spawner','deathSpawn']}],
  ['Fireball',4,'Rare','spell',{damage:690,mechanics:['splash','knockback']}],['Arrows',3,'Common','spell',{damage:360,mechanics:['splash']}],['Rage',2,'Epic','spell',{damage:120,mechanics:['splash','rage']}],['Rocket',6,'Rare','spell',{damage:1250,mechanics:['splash']}],['Goblin Barrel',3,'Epic','spell',{count:3,mechanics:['spawn','burrow']}],['Freeze',4,'Epic','spell',{damage:120,mechanics:['splash','freeze']}],['Mirror',1,'Epic','spell',{mechanics:['clone']}],['Lightning',6,'Epic','spell',{damage:870,mechanics:['chain','stun']}],['Zap',2,'Common','spell',{damage:190,mechanics:['splash','stun']}],['Poison',4,'Epic','spell',{damage:720,mechanics:['splash','dot']}],['Graveyard',5,'Legendary','spell',{count:9,mechanics:['spawn']}],['The Log',2,'Legendary','spell',{damage:290,mechanics:['splash','knockback']}],['Tornado',3,'Epic','spell',{damage:180,mechanics:['splash','pull']}],['Clone',3,'Epic','spell',{mechanics:['clone']}],['Earthquake',3,'Rare','spell',{damage:520,mechanics:['splash','slow']}],['Barbarian Barrel',2,'Epic','spell',{damage:240,mechanics:['splash','spawn','knockback']}],['Giant Snowball',2,'Common','spell',{damage:210,mechanics:['splash','slow','knockback']}],['Royal Delivery',3,'Common','spell',{damage:430,mechanics:['splash','spawn','knockback']}],['Goblin Curse',2,'Epic','spell',{damage:180,mechanics:['dot','transform']}],['Void',3,'Epic','spell',{damage:720,mechanics:['splash']}],['Vines',3,'Epic','spell',{damage:260,mechanics:['pull','stun']}],
];

function slug(name: string): string { return name.toLowerCase().replace(/\./g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); }
function hue(name: string): number { let n=0; for (const c of name) n=(n*31+c.charCodeAt(0))%360; return n; }
function defaults(name: string, cost: number, rarity: Rarity, type: CardType): CardDefinition {
  const h=hue(name); const ranged=/Archer|Musketeer|Wizard|Dragon|Witch|Princess|Bomber|Machine|Firecracker|Hunter|Executioner|Dart|Zapp|Bowler/.test(name);
  return { id:slug(name), name, rarity, type, cost, hp:type==='spell'?1:type==='building'?1500:800+cost*165, damage:110+cost*32, speed:type==='troop'?1:0, range:ranged?5:1.05, hitSpeed:ranged?1.25:1.1, count:1, target:'ground', mechanics:ranged?['ranged']:['melee'], color:`hsl(${h} 68% 48%)`, accent:`hsl(${(h+42)%360} 86% 70%)`, description:'' };
}

export const CARDS: CardDefinition[] = seeds.map(([name,cost,rarity,type,over]) => {
  const d={...defaults(name,cost,rarity,type),...over};
  if (type==='building') { d.speed=0; d.target=d.target ?? 'all'; d.mechanics=[...(over?.mechanics ?? []), 'ranged']; d.hitSpeed=over?.hitSpeed ?? 1.15; d.damage=over?.damage ?? 165+cost*20; d.hp=over?.hp ?? 1000+cost*130; }
  if (type==='spell') { d.speed=0; d.range=3; d.target='all'; d.hp=1; }
  d.description = `${d.mechanics.map(m=>m.replace(/([A-Z])/g,' $1').toLowerCase()).join(' · ')} — ${d.target==='all'?'air & ground':d.target}`;
  return d;
});

export const CARD_MAP = new Map(CARDS.map(c=>[c.id,c]));
export const DEFAULT_DECK = ['knight','archers','giant','fireball','minions','valkyrie','goblin-hut','zap'];
export const AI_DECKS = [
  ['giant','witch','mini-pekka','musketeer','baby-dragon','fireball','arrows','tombstone'],
  ['hog-rider','ice-spirit','firecracker','cannon','skeletons','the-log','earthquake','knight'],
  ['golem','night-witch','baby-dragon','lumberjack','tornado','lightning','mega-minion','barbarian-barrel'],
  ['royal-giant','fisherman','hunter','electro-spirit','phoenix','fireball','the-log','goblin-cage'],
];

export const EVOLUTIONS = ['Knight','Archers','Barbarians','Skeletons','Firecracker','Royal Giant','Mortar','Valkyrie','Ice Spirit','Bats','Bomber','Wall Breakers','Battle Ram','Wizard','Goblin Barrel','Goblin Drill','Goblin Giant','P.E.K.K.A','Mega Knight','Electro Dragon','Musketeer','Cannon','Dart Goblin','Executioner','Lumberjack','Hunter','Witch','Skeleton Army','Furnace','Inferno Dragon','Royal Hogs','Minion Horde','Princess','Skeleton Barrel','Elite Barbarians','Giant Snowball','Goblin Cage','Tesla','Zap','Electro Giant'];
export const HEROES = ['Mini P.E.K.K.A','Musketeer','Wizard','Goblins','Ice Golem','Mega Minion','Barbarian Barrel','Magic Archer','Balloon','Bowler','Tombstone','Valkyrie'];
export const TOWER_TROOPS = ['Tower Princess','Cannoneer','Dagger Duchess','Royal Chef'];

export function getCard(id: string): CardDefinition { const c=CARD_MAP.get(id); if(!c) throw new Error(`Unknown card: ${id}`); return c; }
export function cardPalette(card: CardDefinition): [string,string] { return [card.color || C, card.accent || A]; }
export function has(card: CardDefinition, mechanic: Mechanic): boolean { return card.mechanics.includes(mechanic); }
export const RESEARCHED_CARD_IDS = CARDS.map(c=>c.id);
