import './styles.css';
import './builder.css';
import { CARDS, EVOLUTIONS, HEROES, TOWER_TROOPS, getCard } from './cards';
import { BattleEngine } from './engine';
import { ArenaRenderer } from './renderer';
import { portraitDataUrl } from './models';
import type { Vec2 } from './types';

const root=document.getElementById('game')!;
root.innerHTML=`<div class="shell">
  <header class="topbar"><a class="back" href="/">‹ ARCADE</a><div class="brand"><span>CROWNFALL</span><b>ARENA</b></div><button class="icon-btn" id="sound" aria-label="Toggle sound">♫</button></header>
  <main class="stage">
    <section class="menu" id="menu"><div class="crest"><i></i><span>×</span></div><p class="eyebrow">MICHEL'S ARCADE PRESENTS</p><h1>CROWNFALL<br><em>ARENA</em></h1><p class="lede">Command your deck. Break their guard. Claim the crown.</p><div class="deck-preview" id="deck-preview"></div><div class="menu-actions"><button class="secondary" id="collection">BUILD DECK <small>${CARDS.length} CARDS</small></button><button class="battle-btn" id="battle"><span>BATTLE</span><small>CLASSIC 1v1</small></button></div><p class="mode-note">NORMALIZED LEVEL 11 · ALL CARDS UNLOCKED</p></section>
    <section class="battle hidden" id="battle-screen"><canvas></canvas><div class="opponent"><span class="avatar red"></span><div><b>RIVAL</b><small>STRATEGIST AI</small></div><div class="crowns" id="red-crowns">♛ 0</div></div><div class="timer" id="timer">3:00</div><div class="announcement" id="announcement"></div><div class="player"><span class="avatar blue"></span><div><b>YOU</b><small>CROWN GUARD</small></div><div class="crowns" id="blue-crowns">♛ 0</div></div><div class="hand-wrap"><div class="next-card" id="next-card"></div><div class="hand" id="hand"></div><div class="elixir"><span id="elixir-count">5</span><div class="elixir-track"><i id="elixir-fill"></i><div class="ticks"></div></div><b id="multiplier">×1</b></div></div><button class="debug-toggle" id="debug-toggle">DEV</button><aside class="debug hidden" id="debug"><label><input type="checkbox" id="infinite"> Infinite elixir</label><label><input type="checkbox" id="ranges"> Show ranges</label><label>Speed <input type="range" min=".25" max="4" step=".25" value="1" id="speed"></label><select id="spawn-card"></select><button id="spawn-blue">Spawn friendly</button><button id="spawn-red">Spawn enemy</button><button id="end-match">End match</button></aside></section>
  </main>
  <dialog id="collection-dialog"><div class="collection-head"><div><small>THE WAR ROOM</small><h2>BUILD YOUR DECK</h2><p>Drag cards into a slot. Drag them back to the collection to remove.</p></div><button id="close-collection">×</button></div><div class="deck-builder"><div class="deck-slots" id="deck-slots"></div><div class="deck-stats"><b id="deck-count">8 / 8</b><span id="deck-average">Avg 0.0</span></div></div><div class="filters"><input id="search" placeholder="Search all cards…"><select id="rarity"><option value="">All rarities</option><option>Common</option><option>Rare</option><option>Epic</option><option>Legendary</option><option>Champion</option></select><select id="card-type"><option value="">All types</option><option value="troop">Troops</option><option value="building">Buildings</option><option value="spell">Spells</option></select></div><div class="collection-body"><div class="return-zone" id="return-zone"><b>↙ RETURN CARD</b><span>Drop a deck card here to remove it</span></div><div class="collection-grid" id="collection-grid"></div></div><div class="collection-foot"><span>Choose exactly 8 cards · Drag to reorder</span><button id="save-deck">SAVE DECK</button></div></dialog>
  <div class="result hidden" id="result"><div><small>BATTLE COMPLETE</small><h2 id="result-title">VICTORY</h2><p id="result-score"></p><button id="rematch">REMATCH</button><button class="secondary" id="result-home">MAIN MENU</button></div></div>
</div>`;

let deck=BattleEngine.loadDeck();
let engine:BattleEngine|undefined,renderer:ArenaRenderer|undefined,selected:string|undefined,pointer:Vec2|undefined,dragging=false,deckDropHandled=false,last=performance.now(),audio=true,announced='';
const portraits=new Map<string,string>();
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const portrait=(id:string)=>{let p=portraits.get(id);if(!p){p=portraitDataUrl(getCard(id));portraits.set(id,p);}return p;};

function cardMarkup(id:string,mini=false){const c=getCard(id);return `<button class="card ${c.rarity.toLowerCase()}" data-card="${id}" style="--card:${c.color};--accent:${c.accent}" title="${c.name}: ${c.description}"><i class="cost">${c.cost}</i><span class="sigil"><img src="${portrait(id)}" alt="${c.name}"></span><strong>${c.name}</strong>${mini?'':`<small>${c.type}</small>`}</button>`;}
function renderDeck(){ $('deck-preview').innerHTML=deck.map(id=>cardMarkup(id,true)).join(''); }

function renderBuilder(){
  $('deck-slots').innerHTML=Array.from({length:8},(_,i)=>{const id=deck[i];return `<div class="deck-slot ${id?'filled':''}" data-slot="${i}">${id?cardMarkup(id,true):`<span>${i+1}</span><small>DROP CARD</small>`}</div>`;}).join('');
  const avg=deck.length?deck.reduce((s,id)=>s+getCard(id).cost,0)/deck.length:0;$('deck-count').textContent=`${deck.length} / 8`;$('deck-average').textContent=`Avg ${avg.toFixed(1)} elixir`;$('save-deck').toggleAttribute('disabled',deck.length!==8);
  document.querySelectorAll<HTMLElement>('.deck-slot').forEach(slot=>{slot.ondragover=e=>{e.preventDefault();slot.classList.add('over');};slot.ondragleave=()=>slot.classList.remove('over');slot.ondrop=e=>{e.preventDefault();deckDropHandled=true;slot.classList.remove('over');const payload=parseDrag(e);if(!payload)return;const index=Number(slot.dataset.slot);moveIntoSlot(payload,index);};const card=slot.querySelector<HTMLElement>('.card');if(card){card.draggable=true;card.ondragstart=e=>{deckDropHandled=false;e.dataTransfer!.setData('text/plain',JSON.stringify({source:'deck',index:Number(slot.dataset.slot),id:card.dataset.card}));e.dataTransfer!.effectAllowed='move';slot.classList.add('dragging');};card.ondragend=()=>{slot.classList.remove('dragging');if(!deckDropHandled){deck.splice(Number(slot.dataset.slot),1);renderBuilder();renderCollection();}};card.onclick=()=>{deck.splice(Number(slot.dataset.slot),1);renderBuilder();renderCollection();};}});
}
function parseDrag(e:DragEvent):{source:string;id:string;index?:number}|undefined{try{return JSON.parse(e.dataTransfer?.getData('text/plain')||'');}catch{return undefined;}}
function moveIntoSlot(payload:{source:string;id:string;index?:number},index:number){if(payload.source==='deck'&&payload.index!==undefined){const [id]=deck.splice(payload.index,1);deck.splice(Math.min(index,deck.length),0,id!);}else if(!deck.includes(payload.id)){if(deck.length<8)deck.splice(Math.min(index,deck.length),0,payload.id);else deck[index]=payload.id;}renderBuilder();renderCollection();}
function renderCollection(){
  const q=$<HTMLInputElement>('search').value.toLowerCase(),rar=$<HTMLSelectElement>('rarity').value,type=$<HTMLSelectElement>('card-type').value;const cards=CARDS.filter(c=>(!q||c.name.toLowerCase().includes(q))&&(!rar||c.rarity===rar)&&(!type||c.type===type));
  $('collection-grid').innerHTML=cards.map(c=>`<article class="collection-card ${deck.includes(c.id)?'selected':''}" data-id="${c.id}" draggable="true" style="--card:${c.color};--accent:${c.accent}"><div class="art"><img src="${portrait(c.id)}" alt="${c.name}"><i>${c.cost}</i>${deck.includes(c.id)?'<mark>IN DECK</mark>':''}</div><b>${c.name}</b><small>${c.rarity} · ${c.type}</small><p>${c.description}</p></article>`).join('');
  document.querySelectorAll<HTMLElement>('.collection-card').forEach(el=>{el.ondragstart=e=>{e.dataTransfer!.setData('text/plain',JSON.stringify({source:'collection',id:el.dataset.id}));e.dataTransfer!.effectAllowed='copyMove';};el.onclick=()=>{const id=el.dataset.id!;const i=deck.indexOf(id);if(i>=0)deck.splice(i,1);else if(deck.length<8)deck.push(id);renderBuilder();renderCollection();};});
}
function openBuilder(){renderBuilder();renderCollection();$<HTMLDialogElement>('collection-dialog').showModal();}

function start(){if(deck.length!==8){openBuilder();return;}engine=new BattleEngine(deck);renderer=new ArenaRenderer(engine);$('battle-screen').querySelector('canvas')!.replaceWith(renderer.canvas);$('menu').classList.add('hidden');$('battle-screen').classList.remove('hidden');$('result').classList.add('hidden');setupBattleUI();last=performance.now();requestAnimationFrame(loop);}
function setupBattleUI(){if(!engine)return;const hand=$('hand');hand.innerHTML=engine.blue.hand.map(id=>cardMarkup(id)).join('');hand.querySelectorAll<HTMLElement>('.card').forEach(el=>{el.onpointerdown=ev=>{selected=el.dataset.card;dragging=true;el.setPointerCapture(ev.pointerId);el.classList.add('picked');};el.onpointerup=()=>{if(selected&&pointer)playSelected(pointer);dragging=false;el.classList.remove('picked');};el.onclick=()=>{selected=el.dataset.card;hand.querySelectorAll('.card').forEach(x=>x.classList.toggle('picked',(x as HTMLElement).dataset.card===selected));};});$('next-card').innerHTML=`<small>NEXT</small>${cardMarkup(engine.blue.next,true)}`;}
function playSelected(p:Vec2){if(!engine||!selected)return;if(engine.play({type:'play',team:'blue',cardId:selected,x:p.x,y:p.y})){tone(250,.05);selected=undefined;setupBattleUI();}}
function loop(now:number){if(!engine||!renderer)return;const dt=(now-last)/1000;last=now;engine.update(dt);updateHUD();renderer.render(selected,pointer);if(engine.phase!=='ended')requestAnimationFrame(loop);else showResult();}
function updateHUD(){if(!engine)return;const left=Math.max(0,engine.duration-engine.time),m=Math.floor(left/60),s=Math.floor(left%60);$('timer').textContent=`${m}:${String(s).padStart(2,'0')}`;$('timer').classList.toggle('urgent',left<30);$('elixir-count').textContent=String(Math.floor(engine.blue.elixir));$('elixir-fill').style.width=`${engine.blue.elixir*10}%`;$('multiplier').textContent=`×${engine.multiplier}`;$('blue-crowns').textContent=`♛ ${engine.blue.crowns}`;$('red-crowns').textContent=`♛ ${engine.red.crowns}`;document.querySelectorAll<HTMLElement>('#hand .card').forEach(el=>el.classList.toggle('disabled',getCard(el.dataset.card!).cost>engine!.blue.elixir));const a=engine.events.find(e=>e.type==='announce');if(a&&a.text!==announced){announced=a.text||'';const el=$('announcement');el.textContent=announced;el.classList.remove('show');void el.offsetWidth;el.classList.add('show');tone(520,.2);}}
function showResult(){if(!engine)return;const win=engine.winner==='blue';$('result-title').textContent=engine.winner==='draw'?'DRAW':win?'VICTORY':'DEFEAT';$('result-title').className=win?'win':'loss';$('result-score').textContent=`${engine.blue.crowns} CROWNS · ${engine.red.crowns} CROWNS · ${Math.floor(engine.time/60)}:${String(Math.floor(engine.time%60)).padStart(2,'0')}`;$('result').classList.remove('hidden');tone(win?660:130,.5);}
function tone(freq:number,duration:number){if(!audio)return;const ctx=new AudioContext(),o=ctx.createOscillator(),g=ctx.createGain();o.type='triangle';o.frequency.value=freq;g.gain.setValueAtTime(.07,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+duration);}

renderDeck();$('battle').onclick=start;$('collection').onclick=openBuilder;$('close-collection').onclick=()=>$<HTMLDialogElement>('collection-dialog').close();$('search').oninput=renderCollection;$<HTMLSelectElement>('rarity').onchange=renderCollection;$<HTMLSelectElement>('card-type').onchange=renderCollection;$('save-deck').onclick=()=>{if(deck.length===8){localStorage.setItem('crownfall-deck',JSON.stringify(deck));renderDeck();$<HTMLDialogElement>('collection-dialog').close();}};
const returnZone=$('return-zone');returnZone.ondragover=e=>{e.preventDefault();returnZone.classList.add('over');};returnZone.ondragleave=()=>returnZone.classList.remove('over');returnZone.ondrop=e=>{e.preventDefault();deckDropHandled=true;returnZone.classList.remove('over');const p=parseDrag(e);if(p?.source==='deck'&&p.index!==undefined){deck.splice(p.index,1);renderBuilder();renderCollection();}};
$('battle-screen').onpointermove=e=>{if(renderer)pointer=renderer.screenToWorld(e.clientX,e.clientY);};$('battle-screen').onpointerup=()=>{if(dragging&&pointer)playSelected(pointer);dragging=false;};$('battle-screen').onclick=e=>{if(selected&&renderer&&(e.target as HTMLElement).tagName==='CANVAS')playSelected(renderer.screenToWorld(e.clientX,e.clientY));};
$('sound').onclick=()=>{audio=!audio;$('sound').textContent=audio?'♫':'×';};$('rematch').onclick=start;$('result-home').onclick=()=>location.reload();$('debug-toggle').onclick=()=>$('debug').classList.toggle('hidden');$<HTMLInputElement>('infinite').onchange=e=>{if(engine)engine.debug.infiniteElixir=(e.target as HTMLInputElement).checked;};$<HTMLInputElement>('ranges').onchange=e=>{if(engine)engine.debug.showRanges=(e.target as HTMLInputElement).checked;};$<HTMLInputElement>('speed').oninput=e=>{if(engine)engine.debug.speed=Number((e.target as HTMLInputElement).value);};
$<HTMLSelectElement>('spawn-card').innerHTML=CARDS.map(c=>`<option value="${c.id}">${c.name}</option>`).join('');$('spawn-blue').onclick=()=>{if(engine){const id=$<HTMLSelectElement>('spawn-card').value;engine.blue.hand[0]=id;engine.blue.elixir=10;engine.play({type:'play',team:'blue',cardId:id,x:5,y:20});setupBattleUI();}};$('spawn-red').onclick=()=>{if(engine){const id=$<HTMLSelectElement>('spawn-card').value;engine.red.hand[0]=id;engine.red.elixir=10;engine.play({type:'play',team:'red',cardId:id,x:13,y:10});}};$('end-match').onclick=()=>engine?.forceEnd();
addEventListener('keydown',e=>{if(['1','2','3','4'].includes(e.key)&&engine)selected=engine.blue.hand[Number(e.key)-1];if(e.key==='Escape')selected=undefined;});
console.info(`Crownfall manifest: ${CARDS.length} cards, ${EVOLUTIONS.length} evolutions, ${HEROES.length} heroes, ${TOWER_TROOPS.length} tower troops.`);
