import type { LandmarkPlacement, TrackDefinition } from '../types/track';
import { defineCourse } from './courseFactory';
import { LAYOUTS, type CourseLayout } from './layouts';

const layout = (id: string): CourseLayout => {
  const l = LAYOUTS[id];
  if (!l) throw new Error(`No layout for ${id} (run tools/design-courses.ts)`);
  return l;
};

/**
 * Every course: identity (name, theme, difficulty, road style) here, layout in
 * layouts.ts (course language, generated by tools/design-courses.ts from
 * tools/course-recipes.ts and hand-editable). `tools/check-tracks.ts` validates
 * layouts and drives CPU races; `tools/plot-tracks.ts` draws the maps.
 */

// ================================================================== Sunny Cup (easy)

export const SUNNY_CIRCUIT = defineCourse({
  id: 'sunny-circuit',
  name: 'Sunny Circuit',
  theme: 'meadow',
  difficulty: 'easy',
  seed: 1337,
  ...layout('sunny-circuit'),
  landmarks: (L): LandmarkPlacement[] => [{ type: 'castle', anchor: { distance: L * 0.36, side: 'right', wallOffset: 45 } }, { type: 'arch', anchor: { distance: L * 0.58 }, params: { style: 'banner' } }, { type: 'arch', anchor: { distance: L * 0.84 }, params: { style: 'banner' } }],
});

export const PALM_BAY = defineCourse({
  id: 'palm-bay',
  name: 'Palm Bay',
  theme: 'tropical',
  difficulty: 'easy',
  seed: 201,
  ...layout('palm-bay'),
  crowd: 'stand',
  sea: 'south',
  landmarks: (L): LandmarkPlacement[] => [{ type: 'lighthouse', anchor: { distance: L * 0.47, side: 'left', wallOffset: 30 } }, { type: 'resort', anchor: { distance: L * 0.2, side: 'right', wallOffset: 22 } }, { type: 'arch', anchor: { distance: L * 0.72 }, params: { style: 'bamboo' } }],
});

export const HARVEST_LANE = defineCourse({
  id: 'harvest-lane',
  name: 'Harvest Lane',
  theme: 'farm',
  difficulty: 'easy',
  seed: 202,
  ...layout('harvest-lane'),
  crowd: 'stand',
  landmarks: (L): LandmarkPlacement[] => [{ type: 'barn', anchor: { distance: L * 0.3, side: 'right', wallOffset: 26 } }, { type: 'arch', anchor: { distance: L * 0.66 }, params: { style: 'barnGate' } }],
});

export const MAPLE_GLEN = defineCourse({
  id: 'maple-glen',
  name: 'Maple Glen',
  theme: 'autumn',
  difficulty: 'easy',
  seed: 205,
  ...layout('maple-glen'),
  crowd: 'stand',
  landmarks: (L): LandmarkPlacement[] => [{ type: 'giantTree', anchor: { distance: L * 0.42, side: 'left', wallOffset: 30 } }, { type: 'arch', anchor: { distance: L * 0.18 }, params: { style: 'wood' } }, { type: 'arch', anchor: { distance: L * 0.76 }, params: { style: 'wood' } }],
});

// ================================================================== Splash Cup (medium)


export const CORAL_COVE = defineCourse({
  id: 'coral-cove',
  name: 'Coral Cove',
  theme: 'beach',
  difficulty: 'medium',
  seed: 212,
  roadStyle: 'sand',
  ...layout('coral-cove'),
  crowd: 'none',
  sea: 'east',
  billboards: 0,
  landmarks: (L): LandmarkPlacement[] => [{ type: 'cove', anchor: { distance: L * 0.32, side: 'right', wallOffset: 24 } }, { type: 'cove', anchor: { distance: L * 0.7, side: 'left', wallOffset: 22 }, params: { variant: 1 } }, { type: 'arch', anchor: { distance: L * 0.52 }, params: { style: 'bamboo' } }],
});

export const PINEWOOD_PASS = defineCourse({
  id: 'pinewood-pass',
  name: 'Pinewood Pass',
  theme: 'alpine',
  difficulty: 'medium',
  seed: 203,
  ...layout('pinewood-pass'),
  crowd: 'none',
  billboards: 3,
  landmarks: (L): LandmarkPlacement[] => [{ type: 'sawmill', anchor: { distance: L * 0.36, side: 'left', wallOffset: 26 } }, { type: 'arch', anchor: { distance: L * 0.7 }, params: { style: 'log' } }],
});

export const RIVER_RAPIDS = defineCourse({
  id: 'river-rapids',
  name: 'River Rapids',
  theme: 'river',
  difficulty: 'medium',
  seed: 213,
  ...layout('river-rapids'),
  crowd: 'none',
  billboards: 0,
  landmarks: (L): LandmarkPlacement[] => [{ type: 'waterfall', anchor: { distance: L * 0.5, side: 'right', wallOffset: 30 }, params: { style: 'river' } }, { type: 'sawmill', anchor: { distance: L * 0.15, side: 'left', wallOffset: 30 }, params: { variant: 1 } }, { type: 'arch', anchor: { distance: L * 0.8 }, params: { style: 'rope' } }],
});

export const DUNE_CANYON = defineCourse({
  id: 'dune-canyon',
  name: 'Dune Canyon',
  theme: 'desert',
  difficulty: 'medium',
  seed: 204,
  roadStyle: 'sand',
  ...layout('dune-canyon'),
  crowd: 'stand',
  billboards: 3,
  landmarks: (L): LandmarkPlacement[] => [{ type: 'pyramids', anchor: { distance: L * 0.42, side: 'left', wallOffset: 70 } }, { type: 'arch', anchor: { distance: L * 0.72 }, params: { style: 'sandstone' } }],
});

// ================================================================== Wild Cup (medium)

export const MUSHROOM_HOLLOW = defineCourse({
  id: 'mushroom-hollow',
  name: 'Mushroom Hollow',
  theme: 'mushroom',
  difficulty: 'medium',
  seed: 206,
  ...layout('mushroom-hollow'),
  crowd: 'none',
  billboards: 0,
  landmarks: (L): LandmarkPlacement[] => [{ type: 'giantMushrooms', params: { count: 5 } }, { type: 'giantMushrooms', anchor: { distance: L * 0.55, side: 'right', wallOffset: 30 }, params: { count: 0, grove: true } }],
});

export const TEMPLE_RUINS = defineCourse({
  id: 'temple-ruins',
  name: 'Temple Ruins',
  theme: 'ruins',
  difficulty: 'medium',
  seed: 207,
  roadStyle: 'cobble',
  ...layout('temple-ruins'),
  crowd: 'none',
  billboards: 0,
  landmarks: (L): LandmarkPlacement[] => [{ type: 'stepPyramid', anchor: { distance: L * 0.46, side: 'right', wallOffset: 40 } }, { type: 'arch', anchor: { distance: L * 0.2 }, params: { style: 'stone' } }, { type: 'arch', anchor: { distance: L * 0.76 }, params: { style: 'stone' } }],
});

export const JUNGLE_FALLS = defineCourse({
  id: 'jungle-falls',
  name: 'Jungle Falls',
  theme: 'jungle',
  difficulty: 'medium',
  seed: 214,
  ...layout('jungle-falls'),
  crowd: 'none',
  billboards: 0,
  landmarks: (L): LandmarkPlacement[] => [{ type: 'waterfall', anchor: { distance: L * 0.3, side: 'left', wallOffset: 30 }, params: { style: 'jungle' } }, { type: 'idol', anchor: { distance: L * 0.64, side: 'right', wallOffset: 26 } }, { type: 'arch', anchor: { distance: L * 0.86 }, params: { style: 'vine' } }],
});

export const SUNSET_COAST = defineCourse({
  id: 'sunset-coast',
  name: 'Sunset Coast',
  theme: 'sunset',
  difficulty: 'medium',
  seed: 209,
  ...layout('sunset-coast'),
  traffic: { count: 3, speed: 16 },
  crowd: 'stand',
  sea: 'west',
  landmarks: (L): LandmarkPlacement[] => [{ type: 'boardwalk', anchor: { distance: L * 0.4, side: 'left', wallOffset: 24 } }, { type: 'lighthouse', anchor: { distance: L * 0.8, side: 'right', wallOffset: 30 }, params: { stripes: '#2a4a9a' } }],
});

// ================================================================== Thunder Cup (medium–hard)

export const FROST_PEAK = defineCourse({
  id: 'frost-peak',
  name: 'Frost Peak',
  theme: 'snow',
  difficulty: 'hard',
  seed: 208,
  roadStyle: 'ice',
  ...layout('frost-peak'),
  crowd: 'stand',
  billboards: 3,
  landmarks: (L): LandmarkPlacement[] => [{ type: 'skiLift', anchor: { distance: L * 0.3, side: 'right', wallOffset: 22 } }, { type: 'arch', anchor: { distance: L * 0.62 }, params: { style: 'snow' } }],
});

export const NEON_METRO = defineCourse({
  id: 'neon-metro',
  name: 'Neon Metro',
  theme: 'city',
  difficulty: 'medium',
  seed: 210,
  roadStyle: 'neon',
  ...layout('neon-metro'),
  traffic: { count: 5, speed: 15 },
  billboards: 0,
  landmarks: (L): LandmarkPlacement[] => [{ type: 'neonTower', anchor: { distance: L * 0.45, side: 'left', wallOffset: 30 } }, { type: 'arch', anchor: { distance: L * 0.25 }, params: { style: 'neon' } }, { type: 'arch', anchor: { distance: L * 0.7 }, params: { style: 'neon' } }],
});

export const MOONLIT_MARSH = defineCourse({
  id: 'moonlit-marsh',
  name: 'Moonlit Marsh',
  theme: 'marsh',
  difficulty: 'medium',
  seed: 215,
  roadStyle: 'wood',
  ...layout('moonlit-marsh'),
  billboards: 0,
  landmarks: (L): LandmarkPlacement[] => [{ type: 'marshGraves', anchor: { distance: L * 0.4, side: 'right', wallOffset: 22 } }, { type: 'arch', anchor: { distance: L * 0.15 }, params: { style: 'lantern' } }, { type: 'arch', anchor: { distance: L * 0.74 }, params: { style: 'lantern' } }],
});

export const CLOCKWORK_FACTORY = defineCourse({
  id: 'clockwork-factory',
  name: 'Clockwork Factory',
  theme: 'factory',
  difficulty: 'hard',
  seed: 216,
  ...layout('clockwork-factory'),
  billboards: 0,
  landmarks: (L): LandmarkPlacement[] => [{ type: 'factoryYard' }, { type: 'arch', anchor: { distance: L * 0.2 }, params: { style: 'girder' } }, { type: 'arch', anchor: { distance: L * 0.55 }, params: { style: 'girder' } }, { type: 'arch', anchor: { distance: L * 0.86 }, params: { style: 'girder' } }],
});

// ================================================================== Extreme Cup (hard)

export const VOLCANO_RUN = defineCourse({
  id: 'volcano-run',
  name: 'Volcano Run',
  theme: 'volcano',
  difficulty: 'hard',
  seed: 211,
  ...layout('volcano-run'),
  billboards: 2,
  crowd: 'none',
  landmarks: (L): LandmarkPlacement[] => [{ type: 'arch', anchor: { distance: L * 0.5 }, params: { style: 'obsidian' } }],
});

export const SKY_GARDEN = defineCourse({
  id: 'sky-garden',
  name: 'Sky Garden',
  theme: 'sky',
  difficulty: 'hard',
  seed: 217,
  space: true,
  startHeight: 40,
  ...layout('sky-garden'),
  landmarks: (L): LandmarkPlacement[] => [{ type: 'skyIslands' }, { type: 'arch', anchor: { distance: L * 0.15 }, params: { style: 'ring' } }, { type: 'arch', anchor: { distance: L * 0.4 }, params: { style: 'ring' } }, { type: 'arch', anchor: { distance: L * 0.65 }, params: { style: 'ring' } }, { type: 'arch', anchor: { distance: L * 0.9 }, params: { style: 'ring' } }],
});

export const GLACIER_GAUNTLET = defineCourse({
  id: 'glacier-gauntlet',
  name: 'Glacier Gauntlet',
  theme: 'glacier',
  difficulty: 'hard',
  seed: 218,
  roadStyle: 'ice',
  ...layout('glacier-gauntlet'),
  billboards: 0,
  landmarks: (L): LandmarkPlacement[] => [{ type: 'iceSpires' }, { type: 'arch', anchor: { distance: L * 0.3 }, params: { style: 'ice' } }, { type: 'arch', anchor: { distance: L * 0.7 }, params: { style: 'ice' } }],
});

export const THUNDER_RIDGE = defineCourse({
  id: 'thunder-ridge',
  name: 'Thunder Ridge',
  theme: 'mesa',
  difficulty: 'hard',
  seed: 219,
  ...layout('thunder-ridge'),
  billboards: 0,
  landmarks: (L): LandmarkPlacement[] => [{ type: 'stormTower', anchor: { distance: L * 0.42, side: 'left', wallOffset: 40 } }, { type: 'arch', anchor: { distance: L * 0.7 }, params: { style: 'rock' } }],
});

// ================================================================== Cosmic Cup (hardest)

export const STARLIGHT_HIGHWAY = defineCourse({
  id: 'starlight-highway',
  name: 'Starlight Highway',
  theme: 'starlight',
  difficulty: 'hard',
  seed: 220,
  space: true,
  roadStyle: 'rainbow',
  startHeight: 30,
  ...layout('starlight-highway'),
  landmarks: (L): LandmarkPlacement[] => [{ type: 'spaceStation' }, { type: 'arch', anchor: { distance: L * 0.25 }, params: { style: 'star' } }, { type: 'arch', anchor: { distance: L * 0.75 }, params: { style: 'star' } }],
});

export const MAGMA_CORE = defineCourse({
  id: 'magma-core',
  name: 'Magma Core',
  theme: 'magma',
  difficulty: 'hard',
  seed: 221,
  ...layout('magma-core'),
  billboards: 0,
  landmarks: (L): LandmarkPlacement[] => [{ type: 'magmaCore' }, { type: 'arch', anchor: { distance: L * 0.3 }, params: { style: 'obsidian' } }, { type: 'arch', anchor: { distance: L * 0.68 }, params: { style: 'obsidian' } }],
});

export const COMET_COASTER = defineCourse({
  id: 'comet-coaster',
  name: 'Comet Coaster',
  theme: 'comet',
  difficulty: 'hard',
  seed: 222,
  space: true,
  roadStyle: 'neon',
  startHeight: 30,
  ...layout('comet-coaster'),
  landmarks: (L): LandmarkPlacement[] => [{ type: 'comet' }, { type: 'arch', anchor: { distance: L * 0.2 }, params: { style: 'ring' } }, { type: 'arch', anchor: { distance: L * 0.45 }, params: { style: 'ring' } }, { type: 'arch', anchor: { distance: L * 0.8 }, params: { style: 'ring' } }],
});

export const PRISM_ROAD = defineCourse({
  id: 'prism-road',
  name: 'Prism Road',
  theme: 'prism',
  difficulty: 'hard',
  seed: 223,
  space: true,
  roadStyle: 'rainbow',
  startHeight: 30,
  ...layout('prism-road'),
  landmarks: (L): LandmarkPlacement[] => [{ type: 'prism' }, { type: 'arch', anchor: { distance: L * 0.3 }, params: { style: 'crystal' } }, { type: 'arch', anchor: { distance: L * 0.6 }, params: { style: 'crystal' } }, { type: 'arch', anchor: { distance: L * 0.9 }, params: { style: 'crystal' } }],
});

/** Cup order (and menus) follow this list. */
export const COURSES: TrackDefinition[] = [
  SUNNY_CIRCUIT, PALM_BAY, HARVEST_LANE, MAPLE_GLEN,
  CORAL_COVE, PINEWOOD_PASS, RIVER_RAPIDS, DUNE_CANYON,
  MUSHROOM_HOLLOW, TEMPLE_RUINS, JUNGLE_FALLS, SUNSET_COAST,
  FROST_PEAK, NEON_METRO, MOONLIT_MARSH, CLOCKWORK_FACTORY,
  VOLCANO_RUN, SKY_GARDEN, GLACIER_GAUNTLET, THUNDER_RIDGE,
  STARLIGHT_HIGHWAY, MAGMA_CORE, COMET_COASTER, PRISM_ROAD,
];
