import type { TrackDefinition } from '../types/track';
import { defineCourse } from './courseFactory';
import { LAYOUTS, type CourseLayout } from './layouts';

const layout = (id: string): CourseLayout => {
  const l = LAYOUTS[id];
  if (!l) throw new Error(`No layout for ${id} (run tools/design-courses.ts)`);
  return l;
};

/**
 * Every course: identity (name, theme, difficulty, road style) here, layout in
 * layouts.ts (course language, generated by tools/design-courses.ts from
 * tools/course-recipes.ts and hand-editable). `tools/check-tracks.ts` validates
 * layouts and drives CPU races; `tools/plot-tracks.ts` draws the maps.
 */

// ================================================================== Sunny Cup (easy)

export const SUNNY_CIRCUIT = defineCourse({
  id: 'sunny-circuit',
  name: 'Sunny Circuit',
  theme: 'meadow',
  difficulty: 'easy',
  seed: 1337,
  ...layout('sunny-circuit'),
});

export const PALM_BAY = defineCourse({
  id: 'palm-bay',
  name: 'Palm Bay',
  theme: 'tropical',
  difficulty: 'easy',
  seed: 201,
  ...layout('palm-bay'),
});

export const HARVEST_LANE = defineCourse({
  id: 'harvest-lane',
  name: 'Harvest Lane',
  theme: 'farm',
  difficulty: 'easy',
  seed: 202,
  ...layout('harvest-lane'),
});

export const MAPLE_GLEN = defineCourse({
  id: 'maple-glen',
  name: 'Maple Glen',
  theme: 'autumn',
  difficulty: 'easy',
  seed: 205,
  ...layout('maple-glen'),
});

// ================================================================== Splash Cup (medium)


export const CORAL_COVE = defineCourse({
  id: 'coral-cove',
  name: 'Coral Cove',
  theme: 'tropical',
  difficulty: 'medium',
  seed: 212,
  roadStyle: 'sand',
  ...layout('coral-cove'),
});

export const PINEWOOD_PASS = defineCourse({
  id: 'pinewood-pass',
  name: 'Pinewood Pass',
  theme: 'alpine',
  difficulty: 'medium',
  seed: 203,
  ...layout('pinewood-pass'),
});

export const RIVER_RAPIDS = defineCourse({
  id: 'river-rapids',
  name: 'River Rapids',
  theme: 'alpine',
  difficulty: 'medium',
  seed: 213,
  ...layout('river-rapids'),
});

export const DUNE_CANYON = defineCourse({
  id: 'dune-canyon',
  name: 'Dune Canyon',
  theme: 'desert',
  difficulty: 'medium',
  seed: 204,
  roadStyle: 'sand',
  ...layout('dune-canyon'),
});

// ================================================================== Wild Cup (medium)

export const MUSHROOM_HOLLOW = defineCourse({
  id: 'mushroom-hollow',
  name: 'Mushroom Hollow',
  theme: 'mushroom',
  difficulty: 'medium',
  seed: 206,
  ...layout('mushroom-hollow'),
});

export const TEMPLE_RUINS = defineCourse({
  id: 'temple-ruins',
  name: 'Temple Ruins',
  theme: 'ruins',
  difficulty: 'medium',
  seed: 207,
  roadStyle: 'cobble',
  ...layout('temple-ruins'),
});

export const JUNGLE_FALLS = defineCourse({
  id: 'jungle-falls',
  name: 'Jungle Falls',
  theme: 'ruins',
  difficulty: 'medium',
  seed: 214,
  ...layout('jungle-falls'),
});

export const SUNSET_COAST = defineCourse({
  id: 'sunset-coast',
  name: 'Sunset Coast',
  theme: 'sunset',
  difficulty: 'medium',
  seed: 209,
  ...layout('sunset-coast'),
  traffic: { count: 3, speed: 16 },
});

// ================================================================== Thunder Cup (medium–hard)

export const FROST_PEAK = defineCourse({
  id: 'frost-peak',
  name: 'Frost Peak',
  theme: 'snow',
  difficulty: 'hard',
  seed: 208,
  roadStyle: 'ice',
  ...layout('frost-peak'),
});

export const NEON_METRO = defineCourse({
  id: 'neon-metro',
  name: 'Neon Metro',
  theme: 'city',
  difficulty: 'medium',
  seed: 210,
  roadStyle: 'neon',
  ...layout('neon-metro'),
  traffic: { count: 5, speed: 15 },
});

export const MOONLIT_MARSH = defineCourse({
  id: 'moonlit-marsh',
  name: 'Moonlit Marsh',
  theme: 'mushroom',
  difficulty: 'medium',
  seed: 215,
  roadStyle: 'wood',
  ...layout('moonlit-marsh'),
});

export const CLOCKWORK_FACTORY = defineCourse({
  id: 'clockwork-factory',
  name: 'Clockwork Factory',
  theme: 'city',
  difficulty: 'hard',
  seed: 216,
  ...layout('clockwork-factory'),
});

// ================================================================== Extreme Cup (hard)

export const VOLCANO_RUN = defineCourse({
  id: 'volcano-run',
  name: 'Volcano Run',
  theme: 'volcano',
  difficulty: 'hard',
  seed: 211,
  ...layout('volcano-run'),
});

export const SKY_GARDEN = defineCourse({
  id: 'sky-garden',
  name: 'Sky Garden',
  theme: 'sky',
  difficulty: 'hard',
  seed: 217,
  space: true,
  startHeight: 40,
  ...layout('sky-garden'),
});

export const GLACIER_GAUNTLET = defineCourse({
  id: 'glacier-gauntlet',
  name: 'Glacier Gauntlet',
  theme: 'snow',
  difficulty: 'hard',
  seed: 218,
  roadStyle: 'ice',
  ...layout('glacier-gauntlet'),
});

export const THUNDER_RIDGE = defineCourse({
  id: 'thunder-ridge',
  name: 'Thunder Ridge',
  theme: 'desert',
  difficulty: 'hard',
  seed: 219,
  ...layout('thunder-ridge'),
});

// ================================================================== Cosmic Cup (hardest)

export const STARLIGHT_HIGHWAY = defineCourse({
  id: 'starlight-highway',
  name: 'Starlight Highway',
  theme: 'space',
  difficulty: 'hard',
  seed: 220,
  space: true,
  roadStyle: 'rainbow',
  startHeight: 30,
  ...layout('starlight-highway'),
});

export const MAGMA_CORE = defineCourse({
  id: 'magma-core',
  name: 'Magma Core',
  theme: 'volcano',
  difficulty: 'hard',
  seed: 221,
  ...layout('magma-core'),
});

export const COMET_COASTER = defineCourse({
  id: 'comet-coaster',
  name: 'Comet Coaster',
  theme: 'space',
  difficulty: 'hard',
  seed: 222,
  space: true,
  roadStyle: 'neon',
  startHeight: 30,
  ...layout('comet-coaster'),
});

export const PRISM_ROAD = defineCourse({
  id: 'prism-road',
  name: 'Prism Road',
  theme: 'space',
  difficulty: 'hard',
  seed: 223,
  space: true,
  roadStyle: 'rainbow',
  startHeight: 30,
  ...layout('prism-road'),
});

/** Cup order (and menus) follow this list. */
export const COURSES: TrackDefinition[] = [
  SUNNY_CIRCUIT, PALM_BAY, HARVEST_LANE, MAPLE_GLEN,
  CORAL_COVE, PINEWOOD_PASS, RIVER_RAPIDS, DUNE_CANYON,
  MUSHROOM_HOLLOW, TEMPLE_RUINS, JUNGLE_FALLS, SUNSET_COAST,
  FROST_PEAK, NEON_METRO, MOONLIT_MARSH, CLOCKWORK_FACTORY,
  VOLCANO_RUN, SKY_GARDEN, GLACIER_GAUNTLET, THUNDER_RIDGE,
  STARLIGHT_HIGHWAY, MAGMA_CORE, COMET_COASTER, PRISM_ROAD,
];
