import './styles.css';
import { DIFFICULTIES, FIGHTERS, overall, type Difficulty, type FighterDef } from './data';
import { CageView, type AnimState, type VisualState } from './view';

type Button = 'jab' | 'cross' | 'kick' | 'power' | 'block' | 'takedown' | 'evade' | 'pause';
interface FrameInput { x: number; z: number; held: Record<Button, boolean>; press: Record<Button, boolean>; }
const emptyButtons = (): Record<Button, boolean> => ({ jab: false, cross: false, kick: false, power: false, block: false, takedown: false, evade: false, pause: false });
const root = document.getElementById('game')!;
root.innerHTML = `<canvas class="ck-canvas"></canvas><div class="ck-ui"></div><div class="touch"><div class="stick-zone"><div class="stick-dot"></div></div><div class="touch-btns"><button class="touch-btn grab" data-touch="takedown">GRAB</button><button class="touch-btn cross" data-touch="cross">CROSS</button><button class="touch-btn jab" data-touch="jab">JAB</button><button class="touch-btn power" data-touch="power">POWER</button><button class="touch-btn kick" data-touch="kick">KICK</button><button class="touch-btn block" data-touch="block">BLOCK</button></div></div>`;
const canvas = root.querySelector('canvas')! as HTMLCanvasElement;
const ui = root.querySelector('.ck-ui')! as HTMLDivElement;
const touchLayer = root.querySelector('.touch')! as HTMLDivElement;
const view = new CageView(canvas);

const keys = new Set<string>(); const keyPress = new Set<string>();
addEventListener('keydown', (e) => { if (!keys.has(e.code)) keyPress.add(e.code); keys.add(e.code); if (['Space', 'ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight'].includes(e.code)) e.preventDefault(); });
addEventListener('keyup', (e) => keys.delete(e.code)); addEventListener('blur', () => keys.clear());
let touchX = 0; let touchZ = 0; const touchHeld = emptyButtons(); const touchPressed = emptyButtons();
const zone = root.querySelector('.stick-zone')! as HTMLElement; const dot = root.querySelector('.stick-dot')! as HTMLElement; let stickPointer = -1;
function moveStick(e: PointerEvent): void { const r = zone.getBoundingClientRect(); touchX = Math.max(-1, Math.min(1, (e.clientX - r.left - r.width / 2) / (r.width * .35))); touchZ = Math.max(-1, Math.min(1, (e.clientY - r.top - r.height / 2) / (r.height * .35))); dot.style.transform = `translate(${touchX * 34}px,${touchZ * 34}px)`; }
zone.addEventListener('pointerdown', (e) => { stickPointer = e.pointerId; zone.setPointerCapture(e.pointerId); moveStick(e); }); zone.addEventListener('pointermove', (e) => { if (e.pointerId === stickPointer) moveStick(e); }); zone.addEventListener('pointerup', (e) => { if (e.pointerId === stickPointer) { stickPointer = -1; touchX = touchZ = 0; dot.style.transform = ''; } });
root.querySelectorAll<HTMLElement>('[data-touch]').forEach((el) => { const b = el.dataset.touch as Button; el.addEventListener('pointerdown', (e) => { e.preventDefault(); touchHeld[b] = true; touchPressed[b] = true; el.setPointerCapture(e.pointerId); }); const up = () => { touchHeld[b] = false; }; el.addEventListener('pointerup', up); el.addEventListener('pointercancel', up); });

let previousPad: boolean[][] = [];
const keyMap: Record<Button, string[]> = { jab: ['KeyJ'], cross: ['KeyK'], kick: ['KeyL'], power: ['KeyI'], block: ['Space'], takedown: ['KeyU'], evade: ['ShiftLeft'], pause: ['Escape'] };
function input(player: number): FrameInput {
  const held = emptyButtons(); const press = emptyButtons(); let x = 0; let z = 0;
  const pads = navigator.getGamepads?.() ?? []; const pad = pads[player];
  if (pad) { x = Math.abs(pad.axes[0] ?? 0) > .16 ? (pad.axes[0] ?? 0) : 0; z = Math.abs(pad.axes[1] ?? 0) > .16 ? (pad.axes[1] ?? 0) : 0; const map: Record<Button, number[]> = { jab: [2], cross: [3], kick: [0], power: [1], block: [7], takedown: [5], evade: [6], pause: [9] }; const prev = previousPad[player] ?? []; for (const b of Object.keys(map) as Button[]) { held[b] = map[b].some((i) => !!pad.buttons[i]?.pressed); press[b] = map[b].some((i) => !!pad.buttons[i]?.pressed && !prev[i]); } previousPad[player] = pad.buttons.map((v) => v.pressed); }
  if (player === 0) { x += (keys.has('KeyD') || keys.has('ArrowRight') ? 1 : 0) - (keys.has('KeyA') || keys.has('ArrowLeft') ? 1 : 0); z += (keys.has('KeyS') || keys.has('ArrowDown') ? 1 : 0) - (keys.has('KeyW') || keys.has('ArrowUp') ? 1 : 0); for (const b of Object.keys(keyMap) as Button[]) { held[b] ||= keyMap[b].some((k) => keys.has(k)); press[b] ||= keyMap[b].some((k) => keyPress.has(k)); held[b] ||= touchHeld[b]; press[b] ||= touchPressed[b]; } x += touchX; z += touchZ; }
  const mag = Math.hypot(x, z); if (mag > 1) { x /= mag; z /= mag; } return { x, z, held, press };
}
function clearPresses(): void { keyPress.clear(); for (const b of Object.keys(touchPressed) as Button[]) touchPressed[b] = false; }
function rumble(player: number, power: number, duration = 120): void { const p = navigator.getGamepads?.()[player]; const actuator = p?.vibrationActuator as GamepadHapticActuator | undefined; void actuator?.playEffect?.('dual-rumble', { duration, startDelay: 0, weakMagnitude: power * .55, strongMagnitude: power }); }

class FightAudio {
  private ctx?: AudioContext; private master?: GainNode;
  start(): void { if (!this.ctx) { this.ctx = new AudioContext(); this.master = this.ctx.createGain(); this.master.gain.value = .22; this.master.connect(this.ctx.destination); } void this.ctx.resume(); }
  hit(power: number, blocked: boolean): void { if (!this.ctx || !this.master) return; const t = this.ctx.currentTime; const osc = this.ctx.createOscillator(); const g = this.ctx.createGain(); osc.type = 'triangle'; osc.frequency.setValueAtTime(blocked ? 145 : 78, t); osc.frequency.exponentialRampToValueAtTime(35, t + .09); g.gain.setValueAtTime(.02 + power * .12, t); g.gain.exponentialRampToValueAtTime(.001, t + .11); osc.connect(g).connect(this.master); osc.start(t); osc.stop(t + .12); }
  bell(): void { if (!this.ctx || !this.master) return; for (let i = 0; i < 3; i++) { const o = this.ctx.createOscillator(); const g = this.ctx.createGain(); const t = this.ctx.currentTime + i * .13; o.type = 'sine'; o.frequency.setValueAtTime(860 - i * 80, t); g.gain.setValueAtTime(.2, t); g.gain.exponentialRampToValueAtTime(.001, t + .35); o.connect(g).connect(this.master); o.start(t); o.stop(t + .36); } }
}
const audio = new FightAudio();

interface Attack { id: AnimState; duration: number; hitAt: number; range: number; damage: number; stamina: number; target: 'head' | 'body' | 'legs'; }
const ATTACKS: Record<'jab' | 'cross' | 'kick' | 'power', Attack> = {
  jab: { id: 'jab', duration: .42, hitAt: .19, range: 1.62, damage: 5.6, stamina: 5, target: 'head' },
  cross: { id: 'cross', duration: .58, hitAt: .29, range: 1.68, damage: 9, stamina: 8, target: 'head' },
  kick: { id: 'bodyKick', duration: .72, hitAt: .39, range: 2.02, damage: 10.5, stamina: 11, target: 'body' },
  power: { id: 'headKick', duration: .96, hitAt: .52, range: 2.16, damage: 18, stamina: 19, target: 'head' },
};
interface FighterState { def: FighterDef; x: number; z: number; health: number; head: number; body: number; legs: number; stamina: number; anim: AnimState; animT: number; attack?: Attack; connected: boolean; block: boolean; evade: boolean; hurt: number; knockdowns: number; combo: number; score: number[]; }
const makeFighter = (def: FighterDef, side: number): FighterState => ({ def, x: side * 1.65, z: 0, health: 100, head: 100, body: 100, legs: 100, stamina: 100, anim: 'idle', animT: 0, connected: false, block: false, evade: false, hurt: 0, knockdowns: 0, combo: 0, score: [] });
interface Profile { difficulty: Difficulty; roundLength: number; mode: 'cpu' | 'local'; red: number; blue: number; }
const profile: Profile = (() => { const d: Profile = { difficulty: 'contender', roundLength: 90, mode: 'cpu', red: 0, blue: 2 }; try { return { ...d, ...JSON.parse(localStorage.getItem('cage-kings:profile') ?? '{}') as Partial<Profile> }; } catch { return d; } })();
const save = () => localStorage.setItem('cage-kings:profile', JSON.stringify(profile));

let game: FightGame | undefined; let inMenu = true; let menuIndex = 0; let lastNav = { x: 0, y: 0, a: false, b: false }; let menuReturn = () => mainMenu();
function screen(html: string, cls = ''): HTMLElement { ui.innerHTML = `<div class="screen ${cls}">${html}</div>`; menuIndex = 0; inMenu = true; return ui.firstElementChild! as HTMLElement; }
function padStatus(): string { const p = [...(navigator.getGamepads?.() ?? [])].find(Boolean); return p ? `<span class="pad-pill on">● ${p.id.replace(/\(.*/, '').slice(0, 32)} connected</span>` : `<span class="pad-pill">○ controller ready</span>`; }
function mainMenu(): void {
  game = undefined; touchLayer.classList.remove('in-fight'); view.setFighters(FIGHTERS[profile.red]!, FIGHTERS[profile.blue]!);
  const el = screen(`<span class="corner">MITRIS' ARCADE / 11</span>${padStatus()}<div class="brand"><div class="eyebrow">Original mixed martial arts</div><h1>CAGE <span>KINGS</span></h1><p>Every strike tells a story</p></div><div class="menu"><button class="primary" data-nav data-action="fight">Quick Fight</button><button data-nav data-action="local">Local Versus</button><button data-nav data-action="training">Training</button><button data-nav data-action="settings">Fight Settings</button><button data-nav data-action="controls">Controls</button><a class="btn ghost" data-nav href="/">← Arcade</a></div><div class="footer-tip"><b>Controller:</b> left stick navigate · A select · B back</div>`);
  el.querySelector('[data-action=fight]')!.addEventListener('click', () => { profile.mode = 'cpu'; fighterSelect(); }); el.querySelector('[data-action=local]')!.addEventListener('click', () => { profile.mode = 'local'; fighterSelect(); }); el.querySelector('[data-action=training]')!.addEventListener('click', () => { profile.mode = 'cpu'; startFight(true); }); el.querySelector('[data-action=settings]')!.addEventListener('click', settings); el.querySelector('[data-action=controls]')!.addEventListener('click', controls);
}
function statRows(f: FighterDef): string { return Object.entries(f.stats).map(([k, v]) => `<div class="stat"><span>${k}</span><i><span style="width:${v}%"></span></i><b>${v}</b></div>`).join(''); }
function fighterPanel(f: FighterDef, side: 'left' | 'right'): string { return `<section class="fighter-panel ${side}"><div class="fighter-name">${f.name}</div><div class="nickname">“${f.nick}”</div><div class="record">${f.country} · ${f.record} · OVR ${overall(f)}</div><div class="style">${f.style}</div>${statRows(f)}</section>`; }
function fighterSelect(): void {
  const red = FIGHTERS[profile.red]!; const blue = FIGHTERS[profile.blue]!;
  const cards = FIGHTERS.map((f, i) => `<div class="fighter-card ${i === profile.red ? 'p1' : ''} ${i === profile.blue ? 'p2' : ''}" style="--fc:#${f.color.toString(16).padStart(6, '0')}" data-fighter="${i}" data-nav><em>${overall(f)}</em><b>${f.name}</b><small>${f.style} · ${f.country}</small></div>`).join('');
  const el = screen(`<div class="topline"><div><div class="step">${profile.mode === 'local' ? 'LOCAL VERSUS' : 'QUICK FIGHT'}</div><h2>Choose your fighter</h2></div><button class="ghost" data-back>← Back</button></div><div class="fighter-layout">${fighterPanel(red, 'left')}<div><div class="roster">${cards}</div><div class="versus">RED CORNER <span>VS</span> BLUE CORNER</div><div class="select-actions"><button data-swap>Change blue</button><button class="primary" data-start>Fight now</button></div></div>${fighterPanel(blue, 'right')}</div>`,'select-screen');
  el.querySelectorAll<HTMLElement>('[data-fighter]').forEach((c) => c.addEventListener('click', () => { profile.red = Number(c.dataset.fighter); if (profile.red === profile.blue) profile.blue = (profile.blue + 1) % FIGHTERS.length; save(); fighterSelect(); }));
  el.querySelector('[data-swap]')!.addEventListener('click', () => { profile.blue = (profile.blue + 1) % FIGHTERS.length; if (profile.blue === profile.red) profile.blue = (profile.blue + 1) % FIGHTERS.length; save(); fighterSelect(); }); el.querySelector('[data-start]')!.addEventListener('click', () => startFight(false)); el.querySelector('[data-back]')!.addEventListener('click', mainMenu); menuReturn = mainMenu;
}
function settings(): void { const el = screen(`<div class="settings-card"><div class="step">OPTIONS</div><h2>Fight settings</h2><div class="setting"><span>CPU difficulty</span><select data-diff>${DIFFICULTIES.map((d) => `<option value="${d.id}" ${d.id === profile.difficulty ? 'selected' : ''}>${d.label} — ${d.detail}</option>`).join('')}</select></div><div class="setting"><span>Round length</span><select data-round><option value="60" ${profile.roundLength === 60 ? 'selected' : ''}>1 minute</option><option value="90" ${profile.roundLength === 90 ? 'selected' : ''}>90 seconds</option><option value="180" ${profile.roundLength === 180 ? 'selected' : ''}>3 minutes</option></select></div><p>Championship rules: 3 rounds, 10-point judging, knockouts, submissions and referee stoppages.</p><button data-back>Done</button></div>`); const diff = el.querySelector('[data-diff]')! as HTMLSelectElement; const round = el.querySelector('[data-round]')! as HTMLSelectElement; diff.onchange = () => { profile.difficulty = diff.value as Difficulty; save(); }; round.onchange = () => { profile.roundLength = Number(round.value); save(); }; el.querySelector('[data-back]')!.addEventListener('click', mainMenu); menuReturn = mainMenu; }
function controls(): void { const el = screen(`<div class="controls-card"><div class="step">FIGHT MANUAL</div><h2>Controls</h2><p>Move deliberately. A missed power strike drains much more energy than a clean one.</p><div class="control-grid"><div class="control"><span>Move / circle</span><b class="key">Left stick · WASD</b></div><div class="control"><span>Jab</span><b class="key">□ / X · J</b></div><div class="control"><span>Cross / ground strike</span><b class="key">△ / Y · K</b></div><div class="control"><span>Body kick</span><b class="key">✕ / A · L</b></div><div class="control"><span>Power head kick</span><b class="key">○ / B · I</b></div><div class="control"><span>High / low block</span><b class="key">R2 / RT · Space</b></div><div class="control"><span>Takedown</span><b class="key">R1 / RB · U</b></div><div class="control"><span>Sway / deny takedown</span><b class="key">L2 / LT · Shift</b></div><div class="control"><span>Submission (on ground)</span><b class="key">Hold R1 / RB · U</b></div><div class="control"><span>Pause</span><b class="key">Options · Esc</b></div></div><p>Ground defense: move and press face buttons to escape. Hold block to absorb strikes, but repeated blocks weaken your guard.</p><button data-back>Done</button></div>`); el.querySelector('[data-back]')!.addEventListener('click', mainMenu); menuReturn = mainMenu; }

function menuNavigation(): void {
  if (!inMenu) return; const pad = [...(navigator.getGamepads?.() ?? [])].find(Boolean); if (!pad) return; const x = Math.abs(pad.axes[0] ?? 0) > .6 ? Math.sign(pad.axes[0] ?? 0) : 0; const y = Math.abs(pad.axes[1] ?? 0) > .6 ? Math.sign(pad.axes[1] ?? 0) : 0; const a = !!pad.buttons[0]?.pressed; const b = !!pad.buttons[1]?.pressed; const nav = [...ui.querySelectorAll<HTMLElement>('[data-nav]')].filter((n) => n.offsetParent !== null); if (nav.length && y && y !== lastNav.y) menuIndex = (menuIndex + y + nav.length) % nav.length; nav.forEach((n, i) => n.classList.toggle('focus', i === menuIndex)); if (a && !lastNav.a) nav[menuIndex]?.click(); if (b && !lastNav.b) { const back = ui.querySelector<HTMLElement>('[data-back]'); if (back) back.click(); else menuReturn(); } lastNav = { x, y, a, b };
}
setInterval(menuNavigation, 50);

class FightGame {
  a: FighterState; b: FighterState; round = 1; clock: number; phase: 'intro' | 'fight' | 'between' | 'done' = 'intro'; phaseT = 3.5; ground = false; top = 0; groundT = 0; submission = 0; paused = false; training: boolean; lastTime = performance.now();
  private redStats = { damage: 0, control: 0, knockdowns: 0 }; private blueStats = { damage: 0, control: 0, knockdowns: 0 }; private comboTimer = 0; private aiTimer = 0; private aiPlan: Button | undefined;
  constructor(training: boolean) { this.training = training; this.a = makeFighter(FIGHTERS[profile.red]!, -1); this.b = makeFighter(FIGHTERS[profile.blue]!, 1); this.clock = training ? 9999 : profile.roundLength; view.setFighters(this.a.def, this.b.def); this.renderHud(); audio.start(); audio.bell(); requestAnimationFrame((t) => this.loop(t)); }
  private visual(f: FighterState, other: FighterState): VisualState { const facing = Math.atan2(other.x - f.x, other.z - f.z); return { x: f.x, z: f.z, facing, anim: f.anim, phase: f.attack ? f.animT / f.attack.duration : f.animT, hurt: f.hurt, stamina: f.stamina }; }
  private loop = (now: number): void => { if (game !== this) return; const dt = Math.min(.033, (now - this.lastTime) / 1000); this.lastTime = now; const ia = input(0); const ib = profile.mode === 'local' ? input(1) : this.aiInput(dt); if (ia.press.pause || ib.press.pause) this.togglePause(); if (!this.paused) this.update(dt, ia, ib); view.frame(dt, this.visual(this.a, this.b), this.visual(this.b, this.a)); this.updateHud(); clearPresses(); requestAnimationFrame(this.loop); };
  private aiInput(dt: number): FrameInput { const out: FrameInput = { x: 0, z: 0, held: emptyButtons(), press: emptyButtons() }; if (this.phase !== 'fight') return out; const d = Math.hypot(this.a.x - this.b.x, this.a.z - this.b.z); const level = profile.difficulty === 'rookie' ? .55 : profile.difficulty === 'contender' ? .78 : .94; this.aiTimer -= dt; if (this.aiTimer <= 0) { this.aiTimer = .18 + Math.random() * (1.05 - level * .65); const hurt = this.b.head < 38 || this.b.body < 30; if (this.a.attack && Math.random() < level * .42) this.aiPlan = Math.random() < .55 ? 'block' : 'evade'; else if (d > 2.05) this.aiPlan = 'jab'; else if (hurt && Math.random() < .38) this.aiPlan = 'takedown'; else this.aiPlan = (['jab','cross','kick','power','block','takedown'] as Button[])[Math.floor(Math.random() * (profile.difficulty === 'champion' ? 6 : 5))]; }
    const dx = this.a.x - this.b.x; const dz = this.a.z - this.b.z; const len = Math.max(.1, Math.hypot(dx, dz)); if (d > (this.aiPlan === 'kick' || this.aiPlan === 'power' ? 1.78 : 1.36)) { out.x = dx / len; out.z = dz / len; } else if (this.b.stamina < 18) { out.x = -dx / len; out.z = -dz / len; }
    if (this.aiPlan) { if (this.aiPlan === 'block' || this.aiPlan === 'evade') out.held[this.aiPlan] = true; else { out.press[this.aiPlan] = true; this.aiPlan = undefined; } } return out;
  }
  private update(dt: number, ia: FrameInput, ib: FrameInput): void {
    if (this.phase === 'intro') { this.phaseT -= dt; if (this.phaseT <= 0) { this.phase = 'fight'; this.phaseT = 0; audio.bell(); this.message('FIGHT!', `ROUND ${this.round}`); } return; }
    if (this.phase === 'between') { this.phaseT -= dt; if (this.phaseT <= 0) this.nextRound(); return; } if (this.phase !== 'fight') return;
    if (!this.training) { this.clock -= dt; if (this.clock <= 0) { this.clock = 0; this.endRound(); return; } }
    if (this.ground) this.updateGround(dt, ia, ib); else { this.updateFighter(this.a, this.b, ia, dt, 0); this.updateFighter(this.b, this.a, ib, dt, 1); this.separate(); }
    this.a.hurt = Math.max(0, this.a.hurt - dt * .22); this.b.hurt = Math.max(0, this.b.hurt - dt * .22); this.comboTimer -= dt; if (this.comboTimer <= 0) this.a.combo = 0;
  }
  private updateFighter(f: FighterState, o: FighterState, inp: FrameInput, dt: number, player: number): void {
    f.block = inp.held.block && !f.attack && f.stamina > 1; f.evade = inp.held.evade && !f.attack && f.stamina > 1;
    if (f.attack) { f.animT += dt; if (!f.connected && f.animT >= f.attack.hitAt) { f.connected = true; this.resolveAttack(f, o, f.attack, player); } if (f.animT >= f.attack.duration) { f.attack = undefined; f.anim = f.block ? 'block' : 'idle'; f.animT = 0; } return; }
    if (f.hurt > .82) { f.anim = 'hurt'; f.animT += dt; return; }
    const speed = (1.72 + f.def.stats.cardio / 160) * (f.legs / 100 * .28 + .72) * (f.evade ? 1.35 : 1); const mag = Math.hypot(inp.x, inp.z); if (mag > .08) { f.x += inp.x * speed * dt; f.z += inp.z * speed * dt; const r = Math.hypot(f.x, f.z); if (r > 4.55) { f.x *= 4.55 / r; f.z *= 4.55 / r; } f.anim = 'move'; f.animT += dt; if (f.evade) f.stamina = Math.max(0, f.stamina - dt * 5); } else { f.anim = f.block ? 'block' : 'idle'; f.animT += dt; }
    const attackButton = (['jab','cross','kick','power'] as const).find((b) => inp.press[b]); if (attackButton && f.stamina >= ATTACKS[attackButton].stamina) { const base = ATTACKS[attackButton]; f.attack = { ...base }; f.stamina -= base.stamina; f.anim = base.id; f.animT = 0; f.connected = false; } else if (inp.press.takedown && f.stamina >= 18) this.takedown(f, o, player);
    const regen = (6.3 + f.def.stats.cardio * .045) * (f.block ? .42 : 1); f.stamina = Math.min(100, f.stamina + regen * dt);
  }
  private resolveAttack(f: FighterState, o: FighterState, atk: Attack, player: number): void {
    const d = Math.hypot(o.x - f.x, o.z - f.z); if (d > atk.range || o.evade) { f.stamina = Math.max(0, f.stamina - atk.stamina * .45); return; }
    const blocked = o.block && o.stamina > 0; const stat = atk.id === 'bodyKick' || atk.id === 'headKick' ? f.def.stats.striking : (f.def.stats.striking + f.def.stats.power) / 2; let dmg = atk.damage * (.72 + stat / 250) * (.55 + f.stamina / 220); if (blocked) { o.stamina = Math.max(0, o.stamina - dmg * .72); dmg *= o.stamina > 0 ? .19 : .55; } else { o.stamina = Math.max(0, o.stamina - dmg * .16); }
    if (atk.target === 'head') o.head -= dmg; else if (atk.target === 'body') { o.body -= dmg; o.stamina = Math.max(0, o.stamina - dmg * .65); } else o.legs -= dmg;
    o.health -= dmg * (atk.target === 'head' ? 1 : .62); o.hurt = Math.min(1, o.hurt + dmg / 38); o.anim = blocked ? 'block' : 'hurt'; o.animT = 0; audio.hit(dmg / 18, blocked); view.hitFlash(blocked ? .12 : dmg / 22); rumble(player === 0 ? 1 : 0, Math.min(1, dmg / 14));
    const stats = player === 0 ? this.redStats : this.blueStats; stats.damage += dmg; if (!blocked) { f.combo++; if (player === 0) { this.comboTimer = 1.5; const c = ui.querySelector('.combo')!; c.textContent = `${f.combo} HIT COMBO`; c.classList.toggle('show', f.combo > 1); } }
    const chin = o.def.stats.chin; const koChance = Math.max(0, (dmg - 8) / 55 + (42 - o.head) / 125 - chin / 900); if (!blocked && (o.health <= 0 || o.head <= 0 || Math.random() < koChance)) this.knockdown(f, o, player);
  }
  private knockdown(f: FighterState, o: FighterState, player: number): void { o.knockdowns++; (player === 0 ? this.redStats : this.blueStats).knockdowns++; o.anim = 'ko'; o.animT = 0; o.attack = undefined; rumble(player === 0 ? 1 : 0, 1, 360); if (o.knockdowns >= 2 || o.health <= -5 || o.head <= -8) { this.finish(f, 'KO / TKO'); return; } this.message('KNOCKDOWN!', `${o.def.name} IS HURT`); o.health = Math.max(18, o.health); o.head = Math.max(14, o.head); o.hurt = 1; setTimeout(() => { if (this.phase === 'fight' && !this.ground) { o.anim = 'idle'; o.animT = 0; o.hurt = .55; } }, 1800); }
  private takedown(f: FighterState, o: FighterState, player: number): void { const d = Math.hypot(o.x - f.x, o.z - f.z); f.stamina -= 18; f.anim = 'takedown'; f.animT = 0; const defense = o.evade ? 28 : 0; const chance = .35 + (f.def.stats.grappling - o.def.stats.grappling + defense * -1) / 100 + f.stamina / 300; if (d < 1.7 && Math.random() < chance) { this.ground = true; this.top = player; this.groundT = 9; this.submission = 0; f.anim = 'ground'; o.anim = 'ground'; f.x = o.x = (f.x + o.x) / 2; f.z = o.z = (f.z + o.z) / 2; this.message('TAKEDOWN', `${f.def.name} ON TOP`); } }
  private updateGround(dt: number, ia: FrameInput, ib: FrameInput): void { const top = this.top === 0 ? this.a : this.b; const bot = this.top === 0 ? this.b : this.a; const ti = this.top === 0 ? ia : ib; const bi = this.top === 0 ? ib : ia; this.groundT -= dt; (this.top === 0 ? this.redStats : this.blueStats).control += dt; top.anim = bot.anim = 'ground'; top.stamina = Math.min(100, top.stamina + dt * 3); bot.stamina = Math.min(100, bot.stamina + dt * 2);
    if (ti.press.jab || ti.press.cross || ti.press.power) { const blocked = bi.held.block; const dmg = (blocked ? 2.2 : 5.4) * (.65 + top.def.stats.power / 180); bot.head -= dmg; bot.health -= dmg; top.stamina = Math.max(0, top.stamina - 5); audio.hit(dmg / 10, blocked); view.hitFlash(dmg / 15); if (bot.health <= 0 || bot.head <= 0) { this.finish(top, 'GROUND & POUND TKO'); return; } }
    const escape = Math.hypot(bi.x, bi.z) * dt * .22 + (bi.press.jab || bi.press.cross || bi.press.kick || bi.press.power ? .045 : 0); if (ti.held.takedown && top.stamina > 0) { const edge = (top.def.stats.grappling - bot.def.stats.grappling) / 500; this.submission += dt * (.085 + edge); top.stamina -= dt * 7; } else this.submission -= escape + dt * .018; this.submission = Math.max(-.3, Math.min(1, this.submission)); if (this.submission >= 1) { this.finish(top, 'SUBMISSION'); return; } const gm = ui.querySelector('.ground-meter')!; gm.classList.toggle('on', ti.held.takedown || this.submission > .06); const bar = gm.querySelector('span')! as HTMLElement; bar.style.width = `${Math.max(0, this.submission) * 50}%`; bar.style.background = this.top === 0 ? '#ef263c' : '#438cff';
    if (this.groundT <= 0 || this.submission <= -.25) { this.ground = false; this.submission = 0; top.anim = bot.anim = 'idle'; top.x -= .7; bot.x += .7; gm.classList.remove('on'); }
  }
  private separate(): void { const dx = this.b.x - this.a.x; const dz = this.b.z - this.a.z; const d = Math.max(.001, Math.hypot(dx, dz)); if (d < .88) { const push = (.88 - d) / 2; this.a.x -= dx / d * push; this.a.z -= dz / d * push; this.b.x += dx / d * push; this.b.z += dz / d * push; } }
  private endRound(): void { const red = this.redStats.damage + this.redStats.control * 1.4 + this.redStats.knockdowns * 22; const blue = this.blueStats.damage + this.blueStats.control * 1.4 + this.blueStats.knockdowns * 22; const margin = Math.abs(red - blue); this.a.score.push(red >= blue ? 10 : margin > 30 ? 8 : 9); this.b.score.push(blue > red ? 10 : margin > 30 ? 8 : 9); if (this.round >= 3) { const sa = this.a.score.reduce((x,y) => x+y,0); const sb = this.b.score.reduce((x,y) => x+y,0); this.finish(sa >= sb ? this.a : this.b, 'UNANIMOUS DECISION'); return; } this.phase = 'between'; this.phaseT = 4; audio.bell(); this.message(`END OF ROUND ${this.round}`, `${this.a.score.at(-1)} – ${this.b.score.at(-1)}`); }
  private nextRound(): void { this.round++; this.clock = profile.roundLength; this.phase = 'intro'; this.phaseT = 2.6; this.a.stamina = Math.min(100, this.a.stamina + 42); this.b.stamina = Math.min(100, this.b.stamina + 42); this.a.hurt = this.b.hurt = 0; this.a.x = -1.65; this.b.x = 1.65; this.a.z = this.b.z = 0; this.a.anim = this.b.anim = 'idle'; this.redStats = { damage: 0, control: 0, knockdowns: 0 }; this.blueStats = { damage: 0, control: 0, knockdowns: 0 }; audio.bell(); }
  private finish(winner: FighterState, method: string): void { if (this.phase === 'done') return; this.phase = 'done'; winner.anim = 'win'; const loser = winner === this.a ? this.b : this.a; loser.anim = 'ko'; loser.animT = 0; audio.bell(); setTimeout(() => this.results(winner, method), 1500); }
  private results(winner: FighterState, method: string): void { inMenu = true; const scores = winner.score.length ? winner.score.map((s, i) => `<span>R${i+1} · ${s}–${winner === this.a ? this.b.score[i] : this.a.score[i]}</span>`).join('') : ''; ui.innerHTML = `<div class="result"><div class="result-card"><div class="method">WINNER BY ${method}</div><h2>${winner.def.name}</h2><p>${winner.def.nick} · ${winner.def.country} · ${winner.def.style}</p><div class="scorecards">${scores}</div><button class="primary" data-nav data-rematch>Rematch</button> <button data-nav data-menu>Main menu</button></div></div>`; ui.querySelector('[data-rematch]')!.addEventListener('click', () => startFight(this.training)); ui.querySelector('[data-menu]')!.addEventListener('click', mainMenu); }
  private message(big: string, small: string): void { const m = ui.querySelector('.message')!; m.innerHTML = `<b>${big}</b><span>${small}</span>`; m.classList.add('show'); setTimeout(() => m.classList.remove('show'), 1350); }
  private renderHud(): void { inMenu = false; touchLayer.classList.add('in-fight'); ui.innerHTML = `<div class="hud"><div class="hud-top"><div class="corner-hud red"><div><div class="hud-name">${this.a.def.name}</div><div class="bars"><div class="bar hp"><span></span></div><div class="bar stam"><span></span></div></div><div class="damage"></div></div><div class="portrait">${overall(this.a.def)}</div></div><div class="clock"><strong></strong><small></small></div><div class="corner-hud blue"><div class="portrait">${overall(this.b.def)}</div><div><div class="hud-name">${this.b.def.name}</div><div class="bars"><div class="bar hp"><span></span></div><div class="bar stam"><span></span></div></div><div class="damage"></div></div></div></div><div class="message show"><b>ROUND 1</b><span>PROTECT YOURSELF AT ALL TIMES</span></div><div class="combo"></div><div class="ground-meter"><label>Submission pressure</label><div class="ground-track"><span></span></div></div><div class="help-strip"><span><b>□ X</b> jab</span><span><b>△ Y</b> cross</span><span><b>✕ A</b> body kick</span><span><b>○ B</b> power</span><span><b>R2 RT</b> block</span><span><b>R1 RB</b> takedown</span></div></div>`; }
  private updateHud(): void { const corners = ui.querySelectorAll('.corner-hud'); if (corners.length < 2) return; [[this.a,corners[0]!],[this.b,corners[1]!]].forEach(([fighter, el]) => { const f = fighter as FighterState; const e = el as Element; (e.querySelector('.hp span') as HTMLElement).style.width = `${Math.max(0, f.health)}%`; (e.querySelector('.stam span') as HTMLElement).style.width = `${f.stamina}%`; e.querySelector('.damage')!.textContent = `HEAD ${Math.max(0,Math.round(f.head))} · BODY ${Math.max(0,Math.round(f.body))} · LEG ${Math.max(0,Math.round(f.legs))}`; }); const min = Math.floor(this.clock / 60); const sec = Math.max(0, Math.ceil(this.clock % 60)); ui.querySelector('.clock strong')!.textContent = this.training ? '∞' : `${min}:${sec.toString().padStart(2,'0')}`; ui.querySelector('.clock small')!.textContent = `ROUND ${this.round} / 3`; }
  private togglePause(): void { if (this.phase === 'done') return; this.paused = !this.paused; const old = ui.querySelector('.pause'); if (old) old.remove(); if (this.paused) { inMenu = true; const p = document.createElement('div'); p.className = 'pause'; p.innerHTML = `<div class="pause-box"><div class="step">FIGHT PAUSED</div><h2>CORNER</h2><button data-nav data-resume>Resume</button><button data-nav data-controls>Controls</button><button data-nav data-quit>Quit fight</button></div>`; ui.append(p); p.querySelector('[data-resume]')!.addEventListener('click', () => this.togglePause()); p.querySelector('[data-controls]')!.addEventListener('click', () => { this.paused = false; controls(); }); p.querySelector('[data-quit]')!.addEventListener('click', mainMenu); } else inMenu = false; }
}

function startFight(training: boolean): void { audio.start(); ui.innerHTML = ''; game = new FightGame(training); }

let last = performance.now(); function menuRender(now: number): void { const dt = Math.min(.033, (now-last)/1000); last = now; if (!game) view.frame(dt, undefined, undefined, true); requestAnimationFrame(menuRender); } requestAnimationFrame(menuRender);
mainMenu();
