import{Room,ServerError,type Client}from'@colyseus/core';
import{Match,distance,VENTS,REACTOR,ELECTRICAL}from'../../../client/src/starfall/sim';
import{SF_MAX,SF_VERSION,SfMsg,type SfAction,type SfBegin,type SfConfig,type SfInput,type SfJoin,type SfLobby,type SfSnap,type SfEvent}from'../../../client/src/starfall/net/protocol';
import{claimRoomCode,releaseRoomCode}from'../matchmaking/RoomCodes';
import{LAN_MODE}from'../lan';
interface Member{id:string;name:string;color:number;connected:boolean;index:number;input:SfInput;lastChat:number}
const clean=(v:unknown)=>String(v??'Crew').replace(/[^\p{L}\p{N} _.-]/gu,'').trim().slice(0,16)||'Crew';
const cleanChat=(v:unknown)=>String(v??'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,160);
export class StarfallRoom extends Room{
 override maxClients=SF_MAX;private members=new Map<string,Member>();private hostId='';private phase:SfLobby['phase']='lobby';private game:Match|null=null;private acc=0;private snap=0;private votes=new Map<number,number>();
 private config:SfConfig={players:8,impostors:1,bots:7,crewVision:9,impostorVision:13,killCooldown:24,confirmEjects:true};
 override onCreate(o:SfJoin){this.roomId=claimRoomCode();void this.setPrivate(o?.visibility!=='public');void this.setMetadata({code:this.roomId,game:'starfall'});
  this.onMessage(SfMsg.Hello,c=>{this.sendLobby();if(this.game)this.sendBegin(c)});
  this.onMessage(SfMsg.Config,(c,v:Partial<SfConfig>)=>{if(c.sessionId!==this.hostId||this.phase!=='lobby')return;const humans=this.members.size;this.config.players=Math.max(Math.max(4,humans),Math.min(12,Math.round(v.players??this.config.players)));this.config.bots=Math.max(0,this.config.players-humans);this.config.impostors=(v.impostors===2&&this.config.players>=7?2:1);this.config.crewVision=Math.max(3,Math.min(18,Number(v.crewVision??this.config.crewVision)));this.config.impostorVision=Math.max(4,Math.min(24,Number(v.impostorVision??this.config.impostorVision)));this.config.killCooldown=Math.max(10,Math.min(60,Number(v.killCooldown??this.config.killCooldown)));if(typeof v.confirmEjects==='boolean')this.config.confirmEjects=v.confirmEjects;this.sendLobby()});
  this.onMessage(SfMsg.Start,c=>{if(c.sessionId===this.hostId&&this.phase==='lobby')this.startGame()});
  this.onMessage(SfMsg.Input,(c,v:SfInput)=>{const m=this.members.get(c.sessionId);if(m&&this.phase==='playing')m.input={x:Math.max(-1,Math.min(1,Number(v.x)||0)),z:Math.max(-1,Math.min(1,Number(v.z)||0)),yaw:Number(v.yaw)||0}});
  this.onMessage(SfMsg.Action,(c,v:SfAction)=>this.action(c,v));this.setSimulationInterval(ms=>this.update(ms/1000),1000/30);
 }
 override onJoin(c:Client,o:SfJoin){if(o?.version!==SF_VERSION)throw new ServerError(4000,'Game version mismatch — refresh.');if(this.phase!=='lobby')throw new ServerError(4003,'Match already started.');if(this.members.size>=this.config.players)throw new ServerError(4002,'Lobby full.');const index=this.members.size;this.members.set(c.sessionId,{id:c.sessionId,name:clean(o.name),color:Math.max(0,Math.min(11,Math.round(o.color||index))),connected:true,index,input:{x:0,z:0,yaw:0},lastChat:0});if(!this.hostId)this.hostId=c.sessionId;this.config.bots=Math.max(0,this.config.players-this.members.size);this.sendLobby()}
 override async onDrop(c:Client){const m=this.members.get(c.sessionId);if(m)m.connected=false;this.sendLobby();await this.allowReconnection(c,20)}override onReconnect(c:Client){const m=this.members.get(c.sessionId);if(m)m.connected=true;this.sendLobby();if(this.game)this.sendBegin(c)}
 override onLeave(c:Client){this.members.delete(c.sessionId);if(this.hostId===c.sessionId)this.hostId=this.members.keys().next().value??'';this.sendLobby()}override onDispose(){releaseRoomCode(this.roomId)}
 private sendLobby(){const v:SfLobby={code:this.roomId,phase:this.phase,hostId:this.hostId,config:{...this.config},players:[...this.members.values()].map(m=>({id:m.id,name:m.name,color:m.color,connected:m.connected})),lan:LAN_MODE};this.broadcast(SfMsg.Lobby,v)}
 private startGame(){const members=[...this.members.values()];this.config.bots=Math.max(0,this.config.players-members.length);const names=[...members.map(m=>m.name),...Array.from({length:this.config.bots},(_,i)=>['Nova','Slate','Lime','Rose','Echo','Quartz','Cyan','Marigold'][i]??`Bot ${i+1}`)];const ids=[...Array(this.config.players).keys()].sort(()=>Math.random()-.5).slice(0,this.config.impostors);this.game=new Match('crew',Math.random,{count:this.config.players,impostors:this.config.impostors,humanCount:members.length,names,impostorIds:ids});this.game.killCooldown=this.config.killCooldown;members.forEach((m,i)=>m.index=i);this.phase='playing';this.votes.clear();for(const c of this.clients)this.sendBegin(c);this.sendLobby()}
 private sendBegin(c:Client){const g=this.game,m=this.members.get(c.sessionId);if(!g||!m)return;const me=g.people[m.index]!;const begin:SfBegin={me:m.index,people:g.people.map(p=>({id:p.id,name:p.name,color:p.color,bot:p.bot})),role:me.impostor?'impostor':'crew',partners:me.impostor?g.people.filter(p=>p.impostor&&p.id!==me.id).map(p=>p.id):[],config:{...this.config}};c.send(SfMsg.Begin,begin)}
 private event(e:SfEvent){this.broadcast(SfMsg.Event,e)}
 private action(c:Client,a:SfAction){const g=this.game,m=this.members.get(c.sessionId);if(!g||!m||this.phase!=='playing')return;const p=g.people[m.index]!;
  if(a.k==='kill'){const v=g.people[a.target];if(v&&g.kill(p,v))this.event({k:'kill',text:`${v.name} was eliminated.`,id:v.id});}
  else if(a.k==='report'){const b=g.bodies.find(x=>x.id===a.body&&!x.reported);if(b&&g.callMeeting(p,b))this.votes.clear();}
  else if(a.k==='emergency'){if(g.callMeeting(p))this.votes.clear();}
  else if(a.k==='sabotage'){if(p.impostor&&g.triggerSabotage(a.kind))this.event({k:'sabotage',text:a.kind});}
  else if(a.k==='fix'){if(g.sabotage&&distance(p,g.sabotage==='reactor'?REACTOR:ELECTRICAL)<3)g.fix();}
  else if(a.k==='vent'){if(!p.impostor||!p.alive)return;const i=VENTS.findIndex(v=>distance(p,v)<2);if(i>=0)Object.assign(p,VENTS[(i+1)%VENTS.length]);}
  else if(a.k==='task'){if(distance(p,g.tasks[a.index]!)<3)g.completeFor(p,a.index);}
  else if(a.k==='vote'&&g.phase==='meeting'&&p.alive){this.votes.set(p.id,a.target);const livingHumans=g.people.filter(x=>x.alive&&!x.bot).length;if(this.votes.size>=livingHumans)this.resolveVotes();}
  else if(a.k==='chat'&&g.phase==='meeting'&&p.alive){const text=cleanChat(a.text),now=Date.now();if(!text||now-m.lastChat<650)return;m.lastChat=now;this.event({k:'chat',id:p.id,text});g.chatReplies(text,p).slice(0,2).forEach((reply,i)=>this.clock.setTimeout(()=>{if(this.game?.phase==='meeting')this.event({k:'chat',id:reply.id,text:reply.text});},350+i*480));}
 }
 private resolveVotes(){const g=this.game;if(!g)return;const tally=new Map<number,number>();for(const v of this.votes.values())tally.set(v,(tally.get(v)??0)+1);for(const bot of g.people.filter(p=>p.alive&&p.bot)){const v=g.botVote(bot);tally.set(v,(tally.get(v)??0)+1);}const rows=[...tally].sort((a,b)=>b[1]-a[1]);const id=rows[0]&&rows[0][0]>=0&&rows[0][1]>(rows[1]?.[1]??0)?rows[0][0]:-1;const e=id>=0?g.people[id]:undefined;if(e)e.alive=false;g.phase='play';g.sabotage=null;g.cooldown=this.config.killCooldown;g.checkWin();this.event({k:'eject',text:e?`${e.name} was ejected.`:'No one was ejected.',id:e?.id,impostor:e?.impostor,confirmed:this.config.confirmEjects});this.votes.clear()}
 private update(dt:number){const g=this.game;if(!g)return;this.acc+=dt;while(this.acc>=1/30){this.acc-=1/30;for(const m of this.members.values()){const p=g.people[m.index];if(!p?.alive||g.phase!=='play')continue;const i=m.input,s=4.3/30;g.move(p,(Math.cos(i.yaw)*i.x+Math.sin(i.yaw)*i.z)*s,(-Math.sin(i.yaw)*i.x+Math.cos(i.yaw)*i.z)*s);p.yaw=i.yaw;}if(g.phase==='meeting'){g.meetingTime-=1/30;if(g.meetingTime<=0)this.resolveVotes();}else g.step(1/30);}
  for(const e of g.events.splice(0)){if(e.type==='meeting'){this.votes.clear();this.event({k:'meeting',text:e.text,lines:g.discussion()})}else if(e.type==='result'){this.phase='over';for(const c of this.clients)this.sendSnap(c);this.event({k:'result',text:e.text});this.sendLobby()}else if(e.type==='sabotage')this.event({k:'sabotage',text:e.text});}
  this.snap+=dt;if(this.snap>=.1){this.snap=0;for(const c of this.clients)this.sendSnap(c);}}
 private sendSnap(c:Client){const g=this.game,m=this.members.get(c.sessionId);if(!g||!m)return;const me=g.people[m.index]!;const v:SfSnap={t:g.elapsed,phase:g.phase,people:g.people.map(p=>[p.id,+p.x.toFixed(2),+p.z.toFixed(2),+p.yaw.toFixed(3),(p.alive?1:0)|(p.impostor&&(me.impostor||g.phase==='result')?2:0)]),bodies:g.bodies.map(b=>[b.id,+b.x.toFixed(2),+b.z.toFixed(2),b.reported?1:0]),progress:g.progress,cooldown:g.cooldown,sabotage:g.sabotage,sabotageTime:g.sabotageTime,meetingTime:g.meetingTime,meetingReason:g.meetingReason,winner:g.winner,result:g.result,tasks:g.tasks.map((_,i)=>g.taskDone(me,i)?1:0)};c.send(SfMsg.Snap,v)}
}
