import puppeteer from 'puppeteer-core';
import assert from 'node:assert/strict';
const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--enable-gpu','--ignore-gpu-blocklist','--use-angle=metal'],defaultViewport:{width:1440,height:900}});
const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const load=async()=>{await page.goto(process.argv[2]||'http://127.0.0.1:5188/velora/?test',{waitUntil:'networkidle0',timeout:60000});await page.waitForFunction(()=>window.__velora,{timeout:60000});};
try{
await load();await page.screenshot({path:'/tmp/velora-menu.png'});await page.click('#start');await new Promise(r=>setTimeout(r,400));await page.keyboard.press('Space');await new Promise(r=>setTimeout(r,180));assert.ok(await page.evaluate(()=>window.__velora.playerBody.position.y>.8),'On-foot jump must leave ground');await new Promise(r=>setTimeout(r,800));await page.keyboard.press('KeyF');await page.keyboard.down('KeyW');await new Promise(r=>setTimeout(r,2200));await page.keyboard.up('KeyW');
const driving=await page.evaluate(()=>{const c=window.__velora.state.car;return {speed:c.speed,wheels:c.v.numWheelsOnGround,z:c.b.position.z};});assert.ok(driving.speed>10);assert.equal(driving.wheels,4);assert.ok(driving.z<15);console.log('Keyboard driving / suspension:',driving);
await page.screenshot({path:'/tmp/velora-drive.png'});await page.evaluate(()=>window.__velora.setDay(.7));await new Promise(r=>setTimeout(r,300));await page.screenshot({path:'/tmp/velora-night.png'});await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>window.__velora.state.paused),true);
for(const type of ['sports','sedan','truck','motorcycle']){await load();const data=await page.evaluate(type=>{const g=window.__velora,c=g.parked.find(c=>c.type===type);g.teleport(c.b.position.x-2,c.b.position.z);g.enterExit();g.teleport(4.3,-100);g.keys.add('KeyW');for(let i=0;i<120;i++)g.update(1/60);g.keys.clear();const forward=c.speed;g.keys.add('KeyS');for(let i=0;i<240;i++)g.update(1/60);g.keys.clear();return {type: c.type,forward,reverse:c.speed,hp:c.hp,wheels:c.v.numWheelsOnGround};},type);assert.equal(data.type,type);assert.ok(data.forward>8,JSON.stringify(data));assert.ok(data.reverse< -1,JSON.stringify(data));assert.equal(data.wheels,4);console.log('Handling:',data);}
await load();const jobs=await page.evaluate(()=>{const g=window.__velora;g.enterExit();g.teleport(-13,16);g.startMission();const delivery=g.state.mission?.a.label;g.teleport(-380,475);g.update(1/60);const pay1=g.state.money;g.teleport(13,-80);g.startMission();const rivals=g.cars.filter(c=>c.role==='racer').length;for(const p of g.racePath){g.teleport(p.x,p.z);g.update(1/60);}const pay2=g.state.money;g.teleport(-13,16);g.startMission();g.state.mission.left=.001;g.update(1/60);return {delivery,pay1,rivals,pay2,failed:g.state.mission===null};});assert.deepEqual(jobs,{delivery:'D',pay1:650,rivals:2,pay2:1750,failed:true});console.log('Mission transitions / payouts / timeout:',jobs);
await load();const police=await page.evaluate(()=>{const g=window.__velora;g.enterExit();g.teleport(108,13);g.startMission();g.update(1/60);const startHeat=g.state.heat;const spawned=g.cars.filter(c=>c.role==='police').length;for(let i=0;i<1600&&g.state.mission;i++){for(const c of g.cars.filter(c=>c.role==='police')){c.b.position.set(-475,1,-460);c.b.velocity.setZero();}g.update(1/60);}return {startHeat,spawned,heat:g.state.heat,reward:g.state.money,complete:g.state.mission===null};});assert.equal(police.startHeat,3);assert.ok(police.spawned>0);assert.equal(police.heat,0);assert.equal(police.reward,900);console.log('Police search / escape payout:',police);
await load();const damage=await page.evaluate(()=>{const g=window.__velora;g.enterExit();const c=g.state.car;g.damage(c,85);for(let i=0;i<420;i++)g.update(1/60);const dead=c.dead;g.setHealth(0);g.update(1/60);return {dead,health:g.state.health,car:g.state.car===null,heat:g.state.heat};});assert.deepEqual(damage,{dead:true,health:100,car:true,heat:0});console.log('Fire / explosion / recovery:',damage);
await load();const traffic=await page.evaluate(()=>{const g=window.__velora,c=g.cars.find(c=>c.role==='traffic');g.teleport(c.b.position.x+8,c.b.position.z);const start={x:c.b.position.x,z:c.b.position.z};for(let i=0;i<300;i++)g.update(1/60);return {moved:Math.hypot(c.b.position.x-start.x,c.b.position.z-start.z),hp:c.hp,active:g.cars.filter(c=>c.inWorld).length,total:g.cars.length};});assert.ok(traffic.moved>2);assert.ok(traffic.active<traffic.total);console.log('Traffic / nearby simulation:',traffic);
await load();const signals=await page.evaluate(()=>{const g=window.__velora,c=g.cars.find(c=>c.role==='traffic');c.from=[5,5];c.to=[6,5];c.target={x:87,z:4.3};c.b.position.set(55,1,4.3);c.b.quaternion.setFromEuler(0,Math.PI/2,0);c.b.velocity.setZero();g.teleport(55,8);for(let i=0;i<240;i++)g.update(1/60);const redX=c.b.position.x,redSpeed=c.speed;for(let i=0;i<420;i++)g.update(1/60);return {redX,redSpeed,greenX:c.b.position.x};});console.log('Traffic light stop / release:',signals);assert.ok(signals.redX<87);assert.ok(Math.abs(signals.redSpeed)<.2);assert.ok(signals.greenX>signals.redX+4);
await load();const raceAI=await page.evaluate(()=>{const g=window.__velora;g.enterExit();g.teleport(13,-80);g.startMission();g.teleport(496,496);const racers=g.cars.filter(c=>c.role==='racer');const start=racers.map(c=>({...c.b.position}));for(let i=0;i<9500&&g.state.mission;i++)g.update(1/60);return racers.map((c,i)=>({index:c.raceIndex,pos:{...c.b.position},hp:c.hp,endTime:g.state.time,endHealth:g.state.health,message:document.getElementById('toast').textContent,moved:Math.hypot(c.b.position.x-start[i].x,c.b.position.z-start[i].z)}));});console.log('Natural AI race:',raceAI);assert.ok(raceAI.some(c=>c.index>=8),'An AI racer must finish naturally');
await load();await page.click('#start');const frames=await page.evaluate(()=>new Promise(resolve=>{let last=performance.now();const samples=[];function tick(t){samples.push(t-last);last=t;if(samples.length<120)requestAnimationFrame(tick);else {samples.sort((a,b)=>a-b);resolve({medianMs:samples[60],p95Ms:samples[114],drawCalls:window.__velora.renderer.info.render.calls});}}requestAnimationFrame(tick);}));console.log('Local rendering:',frames);
assert.equal(errors.length,0,errors.join('\n'));console.log('PASS: no browser errors. Screenshots: /tmp/velora-{menu,drive,night}.png');
}finally{await browser.close();}
